/* ============================================================
   FIELD COMPANION — SHOWING DATA   (auto-generated)
   ------------------------------------------------------------
   Generated by build_field_companion.py from the same prepped
   showing dicts that build the packet. This is the ONLY file
   the showing-prep workflow overwrites; the app shell
   (field_companion.html) is never touched per showing.

   DO NOT hand-edit — rerun the generator instead.
   ============================================================ */
window.FC_DATA = {
  "meta": {
    "dateLabel": "Tue, July 28",
    "agent": "Christian Daugherty",
    "deployedAt": "2026-07-28T04:57:05.959190+00:00"
  },
  "appointments": [
    {
      "date": "Tue, July 28",
      "client": {
        "name": "Jake Triarsi",
        "fub_url": "https://jillkbiggs.followupboss.com/2/people/view/189400",
        "meta": "5 properties · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Showing homes",
        "fields": [
          [
            "Budget",
            "$799,000"
          ],
          [
            "Location",
            "Hoboken, NJ"
          ],
          [
            "Home type",
            "Condo"
          ],
          [
            "Timeline",
            "Lease ended June 30th"
          ]
        ],
        "snapshotLines": [
          "$799,000. Showing today (5 properties)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "734 Adams St",
          "addr2": "#3A · Hoboken NJ 07030",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "2 BR / 1 BA",
          "time": "",
          "price": "$550,000",
          "agent": "Soha Fontaine ·  (cell) · Compass NJ",
          "phone": "917-892-8977",
          "zillow": "https://www.zillow.com/homedetails/734-Adams-St-APT-3A-Hoboken-NJ-07030/88857375_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/4/HUDSON_358733.pdf",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "Yes — Confirmed (Auto Confirm)",
          "s2_source": "ShowingTime — Auto Confirm, appointment #885546622, confirmed 6:00 PM – 6:30 PM, Tue 7/28",
          "s3_occupancy": "Vacant (go-and-show)",
          "s3_lb": "Supra",
          "s3_notes": "",
          "snap": [
            [
              "$550K",
              "Asking"
            ],
            [
              "8d",
              "Days on mkt"
            ],
            [
              "$400/mo",
              "HOA/mo"
            ],
            [
              "$5,215",
              "Taxes"
            ],
            [
              "537 sq ft",
              "Sq ft"
            ],
            [
              "$1,024/sq",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/20/26: $550K. No cuts.",
          "s5_ownership": "Bought 2/3/20 @ $375K. Rented @ $3,200/mo (listed/removed 2024 & 2025). Listed for sale 7/20/26. Owned ~6.5 yrs.",
          "s5_hoainc": "",
          "s5_parking": "None",
          "s5_storage": "Common storage in building",
          "s5_hvac": "Wall A/C; baseboard gas heat",
          "s5_laundry": "Common (wash/dry room in lower level)",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "3rd floor walk-up (no elevator per ad remarks)",
          "s6_age": "1910",
          "s6_units": "22",
          "s6_amenities": "Intercom; shared backyard",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Jake Triarsi"
        },
        {
          "seq": "2",
          "addr1": "73 Madison St",
          "addr2": "#1S · Hoboken NJ 07030",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "2 BR / 1 BA",
          "time": "",
          "price": "$725,000",
          "agent": "Thomas Kramer ·  (cell) · Weichert Realtors",
          "phone": "201-458-3476",
          "zillow": "https://www.zillow.com/homedetails/73-Madison-St-APT-1S-Hoboken-NJ-07030/38882435_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/5/HUDSON_359982.pdf",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "Awaiting confirmation",
          "s2_source": "ShowingTime — Auto Confirm listing (MLS 260013775, Active, 73 Madison St #1S); no appointment found for 7/28. Needs booking — will Auto Confirm instantly once scheduled.",
          "s3_occupancy": "Vacant",
          "s3_lb": "",
          "s3_notes": "",
          "snap": [
            [
              "$725K",
              "Asking"
            ],
            [
              "14d",
              "Days on mkt"
            ],
            [
              "$440/mo",
              "HOA/mo"
            ],
            [
              "$6,872",
              "Taxes"
            ],
            [
              "702 sq ft",
              "Sq ft"
            ],
            [
              "$1,033/sq",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/14/26: $725K. No cuts.",
          "s5_ownership": "Bought 5/15/23 @ $650K. No rental history on Zillow. Owned ~2.2 yrs.",
          "s5_hoainc": "Water",
          "s5_parking": "None (parking nearby for additional fee per broker remarks)",
          "s5_storage": "Private storage in building",
          "s5_hvac": "Wall A/C; baseboard heat",
          "s5_laundry": "Common W/D room in building",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "",
          "s6_age": "1883",
          "s6_units": "6",
          "s6_amenities": "Intercom; private backyard",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Jake Triarsi"
        },
        {
          "seq": "3",
          "addr1": "132 Jackson St",
          "addr2": "#1N · Hoboken NJ 07030",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "2 BR / 1 BA",
          "time": "",
          "price": "$715,000",
          "agent": "Anthony Packwood ·  (cell) · Engel & Volkers Hoboken",
          "phone": "929-309-5530",
          "zillow": "https://www.zillow.com/homedetails/132-Jackson-St-APT-1N-Hoboken-NJ-07030/38882700_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/9/HUDSON_358294.pdf",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "UNVERIFIED: listing CND, not in ShowingTime — confirm with LA",
          "s2_source": "ShowingTime returned 0 results for MLS 260012699 (CND per MLS ~7/22/26). Confirm with LA Anthony Packwood · 929-309-5530.",
          "s3_occupancy": "Unknown — CND listing not in ShowingTime",
          "s3_lb": "No mention · No mention",
          "s3_notes": "Property under contract (CND). Confirm whether backup showing is proceeding and how to access with LA: Anthony Packwood · 929-309-5530.",
          "snap": [
            [
              "$715K",
              "Asking"
            ],
            [
              "22d",
              "Days on mkt"
            ],
            [
              "$325/mo",
              "HOA/mo"
            ],
            [
              "$5,682",
              "Taxes"
            ],
            [
              "670 sq ft",
              "Sq ft"
            ],
            [
              "$1,067/sq",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 6/30/26: $715K. Listing removed 7/22/26 (off market — note for coordinator).",
          "s5_ownership": "Bought 4/5/21 @ $455K. No rental history on Redfin. Owned ~5.3 yrs.",
          "s5_hoainc": "Water",
          "s5_parking": "None",
          "s5_storage": "Private basement storage",
          "s5_hvac": "Central A/C; hot air (electric)",
          "s5_laundry": "In-unit W/D",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "STATUS: Conditional (under contract ~7/22/26). Unit has private terrace.",
          "s6_age": "1986",
          "s6_units": "6",
          "s6_amenities": "Terrace (unit-specific); private backyard",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Jake Triarsi"
        },
        {
          "seq": "4",
          "addr1": "84 Monroe St",
          "addr2": "#3 · Hoboken NJ 07030",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "2 BR / 1 BA",
          "time": "",
          "price": "$674,000",
          "agent": "Margaret M Crimmins ·  (cell) · Corcoran Sawyer Smith",
          "phone": "201-240-6531",
          "zillow": "https://www.zillow.com/homedetails/84-Monroe-St-APT-3-Hoboken-NJ-07030/38882355_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/0/HUDSON_355927.pdf",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "UNVERIFIED: listing CND, not in ShowingTime — confirm with LA",
          "s2_source": "ShowingTime returned 0 results for MLS 260011070 (CND per MLS ~7/27/26). Confirm with LA Margaret M Crimmins · 201-240-6531.",
          "s3_occupancy": "Unknown — CND listing not in ShowingTime",
          "s3_lb": "No mention · No mention",
          "s3_notes": "Property under contract (CND) as of today. Confirm whether backup showing is proceeding and how to access with LA: Margaret M Crimmins · 201-240-6531.",
          "snap": [
            [
              "$674K",
              "Asking"
            ],
            [
              "48d",
              "Days on mkt"
            ],
            [
              "$509/mo",
              "HOA/mo"
            ],
            [
              "$6,695 (2025)",
              "Taxes"
            ],
            [
              "830 sq ft",
              "Sq ft"
            ],
            [
              "$812/sq",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 6/9/26: $700K → Price changed 7/13/26: $674K (−$26K). Removed 7/27/26 (off market — note for coordinator).",
          "s5_ownership": "Bought 7/1/21 @ $535K. No rental history on Redfin. Owned ~5 yrs.",
          "s5_hoainc": "Water",
          "s5_parking": "None",
          "s5_storage": "",
          "s5_hvac": "Wall A/C; baseboard heat",
          "s5_laundry": "In-unit W/D",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "STATUS: Conditional (under contract ~7/27/26).",
          "s6_age": "1901",
          "s6_units": "5",
          "s6_amenities": "Intercom",
          "s6_projects": "Hallway in process of being painted (per broker remarks)",
          "s6_assess": "$370,900 (2025)",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Jake Triarsi"
        },
        {
          "seq": "5",
          "addr1": "717 Willow Ave",
          "addr2": "#2 · Hoboken NJ 07030",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "2 BR / 1 BA",
          "time": "",
          "price": "$650,000",
          "agent": "Colleen Kraus · KP&G NJ ·  (contact: Matt Kraus per broker remarks)",
          "phone": "973-891-0616",
          "zillow": "https://www.zillow.com/homedetails/717-Willow-Ave-APT-2-Hoboken-NJ-07030/88857654_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/0/HUDSON_362177.pdf",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "Awaiting confirmation",
          "s2_source": "ShowingTime — Auto Confirm listing (MLS 260014550, Active, 717 Willow Ave #2); no appointment found for 7/28. Needs booking — will Auto Confirm instantly once scheduled.",
          "s3_occupancy": "Vacant (virtually staged per broker remarks)",
          "s3_lb": "",
          "s3_notes": "",
          "snap": [
            [
              "$650K",
              "Asking"
            ],
            [
              "7d",
              "Days on mkt"
            ],
            [
              "$451/mo",
              "HOA/mo"
            ],
            [
              "$6,733 (2025)",
              "Taxes"
            ],
            [
              "800 sq ft",
              "Sq ft"
            ],
            [
              "$813/sq",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/23/26: $650K. No cuts.",
          "s5_ownership": "Bought 12/14/20 @ $530K. No rental history on Zillow. Owned ~5.6 yrs.",
          "s5_hoainc": "Heat, water, hot water",
          "s5_parking": "None",
          "s5_storage": "Deeded private basement storage",
          "s5_hvac": "Window A/C; radiator heat (heat included in HOA)",
          "s5_laundry": "In-unit W/D",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "Split-bedroom layout. Shared backyard w/ patio furniture and grills.",
          "s6_age": "1900",
          "s6_units": "10",
          "s6_amenities": "Intercom; shared backyard with patio and grills",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Jake Triarsi"
        }
      ]
    }
  ],
  "client": {
    "name": "Jake Triarsi",
    "fub_url": "https://jillkbiggs.followupboss.com/2/people/view/189400",
    "meta": "5 properties · Buyer · Christian Daugherty, Jill Biggs Group",
    "stage": "Showing homes",
    "fields": [
      [
        "Budget",
        "$799,000"
      ],
      [
        "Location",
        "Hoboken, NJ"
      ],
      [
        "Home type",
        "Condo"
      ],
      [
        "Timeline",
        "Lease ended June 30th"
      ]
    ],
    "snapshotLines": [
      "$799,000. Showing today (5 properties)."
    ]
  },
  "props": [
    {
      "seq": "1",
      "addr1": "734 Adams St",
      "addr2": "#3A · Hoboken NJ 07030",
      "type": "Condominium",
      "ptype": "condo",
      "beds": "2 BR / 1 BA",
      "time": "",
      "price": "$550,000",
      "agent": "Soha Fontaine ·  (cell) · Compass NJ",
      "phone": "917-892-8977",
      "zillow": "https://www.zillow.com/homedetails/734-Adams-St-APT-3A-Hoboken-NJ-07030/88857375_zpid/",
      "nav_addr": "",
      "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/4/HUDSON_358733.pdf",
      "flags": [],
      "s1_time": "",
      "s2_confirmed": "Yes — Confirmed (Auto Confirm)",
      "s2_source": "ShowingTime — Auto Confirm, appointment #885546622, confirmed 6:00 PM – 6:30 PM, Tue 7/28",
      "s3_occupancy": "Vacant (go-and-show)",
      "s3_lb": "Supra",
      "s3_notes": "",
      "snap": [
        [
          "$550K",
          "Asking"
        ],
        [
          "8d",
          "Days on mkt"
        ],
        [
          "$400/mo",
          "HOA/mo"
        ],
        [
          "$5,215",
          "Taxes"
        ],
        [
          "537 sq ft",
          "Sq ft"
        ],
        [
          "$1,024/sq",
          "Per sq ft"
        ]
      ],
      "s5_history": "Listed 7/20/26: $550K. No cuts.",
      "s5_ownership": "Bought 2/3/20 @ $375K. Rented @ $3,200/mo (listed/removed 2024 & 2025). Listed for sale 7/20/26. Owned ~6.5 yrs.",
      "s5_hoainc": "",
      "s5_parking": "None",
      "s5_storage": "Common storage in building",
      "s5_hvac": "Wall A/C; baseboard gas heat",
      "s5_laundry": "Common (wash/dry room in lower level)",
      "s5_flood": "Zone AE (Yes)",
      "s5_misc": "3rd floor walk-up (no elevator per ad remarks)",
      "s6_age": "1910",
      "s6_units": "22",
      "s6_amenities": "Intercom; shared backyard",
      "s6_projects": "",
      "s6_assess": "",
      "s6_financing": "",
      "s6_key": "",
      "similar": [],
      "commute": [],
      "client_name": "Jake Triarsi"
    },
    {
      "seq": "2",
      "addr1": "73 Madison St",
      "addr2": "#1S · Hoboken NJ 07030",
      "type": "Condominium",
      "ptype": "condo",
      "beds": "2 BR / 1 BA",
      "time": "",
      "price": "$725,000",
      "agent": "Thomas Kramer ·  (cell) · Weichert Realtors",
      "phone": "201-458-3476",
      "zillow": "https://www.zillow.com/homedetails/73-Madison-St-APT-1S-Hoboken-NJ-07030/38882435_zpid/",
      "nav_addr": "",
      "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/5/HUDSON_359982.pdf",
      "flags": [],
      "s1_time": "",
      "s2_confirmed": "Awaiting confirmation",
      "s2_source": "ShowingTime — Auto Confirm listing (MLS 260013775, Active, 73 Madison St #1S); no appointment found for 7/28. Needs booking — will Auto Confirm instantly once scheduled.",
      "s3_occupancy": "Vacant",
      "s3_lb": "",
      "s3_notes": "",
      "snap": [
        [
          "$725K",
          "Asking"
        ],
        [
          "14d",
          "Days on mkt"
        ],
        [
          "$440/mo",
          "HOA/mo"
        ],
        [
          "$6,872",
          "Taxes"
        ],
        [
          "702 sq ft",
          "Sq ft"
        ],
        [
          "$1,033/sq",
          "Per sq ft"
        ]
      ],
      "s5_history": "Listed 7/14/26: $725K. No cuts.",
      "s5_ownership": "Bought 5/15/23 @ $650K. No rental history on Zillow. Owned ~2.2 yrs.",
      "s5_hoainc": "Water",
      "s5_parking": "None (parking nearby for additional fee per broker remarks)",
      "s5_storage": "Private storage in building",
      "s5_hvac": "Wall A/C; baseboard heat",
      "s5_laundry": "Common W/D room in building",
      "s5_flood": "Zone AE (Yes)",
      "s5_misc": "",
      "s6_age": "1883",
      "s6_units": "6",
      "s6_amenities": "Intercom; private backyard",
      "s6_projects": "",
      "s6_assess": "",
      "s6_financing": "",
      "s6_key": "",
      "similar": [],
      "commute": [],
      "client_name": "Jake Triarsi"
    },
    {
      "seq": "3",
      "addr1": "132 Jackson St",
      "addr2": "#1N · Hoboken NJ 07030",
      "type": "Condominium",
      "ptype": "condo",
      "beds": "2 BR / 1 BA",
      "time": "",
      "price": "$715,000",
      "agent": "Anthony Packwood ·  (cell) · Engel & Volkers Hoboken",
      "phone": "929-309-5530",
      "zillow": "https://www.zillow.com/homedetails/132-Jackson-St-APT-1N-Hoboken-NJ-07030/38882700_zpid/",
      "nav_addr": "",
      "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/9/HUDSON_358294.pdf",
      "flags": [],
      "s1_time": "",
      "s2_confirmed": "UNVERIFIED: listing CND, not in ShowingTime — confirm with LA",
      "s2_source": "ShowingTime returned 0 results for MLS 260012699 (CND per MLS ~7/22/26). Confirm with LA Anthony Packwood · 929-309-5530.",
      "s3_occupancy": "Unknown — CND listing not in ShowingTime",
      "s3_lb": "No mention · No mention",
      "s3_notes": "Property under contract (CND). Confirm whether backup showing is proceeding and how to access with LA: Anthony Packwood · 929-309-5530.",
      "snap": [
        [
          "$715K",
          "Asking"
        ],
        [
          "22d",
          "Days on mkt"
        ],
        [
          "$325/mo",
          "HOA/mo"
        ],
        [
          "$5,682",
          "Taxes"
        ],
        [
          "670 sq ft",
          "Sq ft"
        ],
        [
          "$1,067/sq",
          "Per sq ft"
        ]
      ],
      "s5_history": "Listed 6/30/26: $715K. Listing removed 7/22/26 (off market — note for coordinator).",
      "s5_ownership": "Bought 4/5/21 @ $455K. No rental history on Redfin. Owned ~5.3 yrs.",
      "s5_hoainc": "Water",
      "s5_parking": "None",
      "s5_storage": "Private basement storage",
      "s5_hvac": "Central A/C; hot air (electric)",
      "s5_laundry": "In-unit W/D",
      "s5_flood": "Zone AE (Yes)",
      "s5_misc": "STATUS: Conditional (under contract ~7/22/26). Unit has private terrace.",
      "s6_age": "1986",
      "s6_units": "6",
      "s6_amenities": "Terrace (unit-specific); private backyard",
      "s6_projects": "",
      "s6_assess": "",
      "s6_financing": "",
      "s6_key": "",
      "similar": [],
      "commute": [],
      "client_name": "Jake Triarsi"
    },
    {
      "seq": "4",
      "addr1": "84 Monroe St",
      "addr2": "#3 · Hoboken NJ 07030",
      "type": "Condominium",
      "ptype": "condo",
      "beds": "2 BR / 1 BA",
      "time": "",
      "price": "$674,000",
      "agent": "Margaret M Crimmins ·  (cell) · Corcoran Sawyer Smith",
      "phone": "201-240-6531",
      "zillow": "https://www.zillow.com/homedetails/84-Monroe-St-APT-3-Hoboken-NJ-07030/38882355_zpid/",
      "nav_addr": "",
      "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/0/HUDSON_355927.pdf",
      "flags": [],
      "s1_time": "",
      "s2_confirmed": "UNVERIFIED: listing CND, not in ShowingTime — confirm with LA",
      "s2_source": "ShowingTime returned 0 results for MLS 260011070 (CND per MLS ~7/27/26). Confirm with LA Margaret M Crimmins · 201-240-6531.",
      "s3_occupancy": "Unknown — CND listing not in ShowingTime",
      "s3_lb": "No mention · No mention",
      "s3_notes": "Property under contract (CND) as of today. Confirm whether backup showing is proceeding and how to access with LA: Margaret M Crimmins · 201-240-6531.",
      "snap": [
        [
          "$674K",
          "Asking"
        ],
        [
          "48d",
          "Days on mkt"
        ],
        [
          "$509/mo",
          "HOA/mo"
        ],
        [
          "$6,695 (2025)",
          "Taxes"
        ],
        [
          "830 sq ft",
          "Sq ft"
        ],
        [
          "$812/sq",
          "Per sq ft"
        ]
      ],
      "s5_history": "Listed 6/9/26: $700K → Price changed 7/13/26: $674K (−$26K). Removed 7/27/26 (off market — note for coordinator).",
      "s5_ownership": "Bought 7/1/21 @ $535K. No rental history on Redfin. Owned ~5 yrs.",
      "s5_hoainc": "Water",
      "s5_parking": "None",
      "s5_storage": "",
      "s5_hvac": "Wall A/C; baseboard heat",
      "s5_laundry": "In-unit W/D",
      "s5_flood": "Zone AE (Yes)",
      "s5_misc": "STATUS: Conditional (under contract ~7/27/26).",
      "s6_age": "1901",
      "s6_units": "5",
      "s6_amenities": "Intercom",
      "s6_projects": "Hallway in process of being painted (per broker remarks)",
      "s6_assess": "$370,900 (2025)",
      "s6_financing": "",
      "s6_key": "",
      "similar": [],
      "commute": [],
      "client_name": "Jake Triarsi"
    },
    {
      "seq": "5",
      "addr1": "717 Willow Ave",
      "addr2": "#2 · Hoboken NJ 07030",
      "type": "Condominium",
      "ptype": "condo",
      "beds": "2 BR / 1 BA",
      "time": "",
      "price": "$650,000",
      "agent": "Colleen Kraus · KP&G NJ ·  (contact: Matt Kraus per broker remarks)",
      "phone": "973-891-0616",
      "zillow": "https://www.zillow.com/homedetails/717-Willow-Ave-APT-2-Hoboken-NJ-07030/88857654_zpid/",
      "nav_addr": "",
      "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/0/HUDSON_362177.pdf",
      "flags": [],
      "s1_time": "",
      "s2_confirmed": "Awaiting confirmation",
      "s2_source": "ShowingTime — Auto Confirm listing (MLS 260014550, Active, 717 Willow Ave #2); no appointment found for 7/28. Needs booking — will Auto Confirm instantly once scheduled.",
      "s3_occupancy": "Vacant (virtually staged per broker remarks)",
      "s3_lb": "",
      "s3_notes": "",
      "snap": [
        [
          "$650K",
          "Asking"
        ],
        [
          "7d",
          "Days on mkt"
        ],
        [
          "$451/mo",
          "HOA/mo"
        ],
        [
          "$6,733 (2025)",
          "Taxes"
        ],
        [
          "800 sq ft",
          "Sq ft"
        ],
        [
          "$813/sq",
          "Per sq ft"
        ]
      ],
      "s5_history": "Listed 7/23/26: $650K. No cuts.",
      "s5_ownership": "Bought 12/14/20 @ $530K. No rental history on Zillow. Owned ~5.6 yrs.",
      "s5_hoainc": "Heat, water, hot water",
      "s5_parking": "None",
      "s5_storage": "Deeded private basement storage",
      "s5_hvac": "Window A/C; radiator heat (heat included in HOA)",
      "s5_laundry": "In-unit W/D",
      "s5_flood": "Zone AE (Yes)",
      "s5_misc": "Split-bedroom layout. Shared backyard w/ patio furniture and grills.",
      "s6_age": "1900",
      "s6_units": "10",
      "s6_amenities": "Intercom; shared backyard with patio and grills",
      "s6_projects": "",
      "s6_assess": "",
      "s6_financing": "",
      "s6_key": "",
      "similar": [],
      "commute": [],
      "client_name": "Jake Triarsi"
    }
  ],
  "history": [
    {
      "deployedAt": "2026-07-27T04:03:25.806424+00:00",
      "meta": {
        "dateLabel": "Mon, July 27",
        "agent": "Christian Daugherty"
      },
      "client": {
        "name": "Elle Dong",
        "fub_url": "https://jillkbiggs.followupboss.com/2/people/view/177066",
        "meta": "1 property · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Appointment set",
        "fields": [
          [
            "Budget",
            "$599,000"
          ],
          [
            "Location",
            "West New York, NJ"
          ]
        ],
        "snapshotLines": [
          "$599,000. Showing today (1 property)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "24 Ave at Port Imperial #B37",
          "addr2": "West New York, NJ 07093",
          "type": "Condo",
          "ptype": "condo",
          "beds": "1 bed / 1 bath",
          "time": "",
          "price": "$575,000",
          "agent": "Mahesh",
          "phone": "929-389-5710",
          "zillow": "https://www.zillow.com/homedetails/24-Avenue-At-Port-Imperial-B37-West-New-York-NJ-07093/2093437559_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/3/HUDSON_360531.pdf",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "Yes — Confirmed (go-and-show)",
          "s2_source": "Broker remarks: Vacant, go and show. ShowingTime login not accessible this run (occluded window); go-and-show confirmed from MLS broker remarks.",
          "s3_occupancy": "Vacant (go-and-show)",
          "s3_lb": "Not found · Not found",
          "s3_notes": "Not found",
          "snap": [
            [
              "$575K",
              "Asking"
            ],
            [
              "12d",
              "Days on mkt"
            ],
            [
              "$597/mo",
              "HOA/mo"
            ],
            [
              "$10,500/yr (2026)",
              "Taxes"
            ],
            [
              "767 sq ft",
              "Sq ft"
            ],
            [
              "$750/sq",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 5/28: $599K → Price cut 7/15: $575K (-$24K). Actual DOM: 59 days (on market since 5/28/2026)",
          "s5_ownership": "Bought 8/31/22 @ $525K. Owned ~3 yrs 11 mos. No rental history on Zillow. (Prior sale: 6/20/2007 @ $450K.)",
          "s5_hoainc": "Parking",
          "s5_parking": "1 Car, Covered Garage (included in HOA)",
          "s5_storage": "No mention",
          "s5_hvac": "Central AC; heat type not specified — verify at showing",
          "s5_laundry": "In-unit",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "",
          "s6_age": "2004",
          "s6_units": "344 (Hudson Club complex at 24 and 26 Ave at Port Imperial — per hudsonnest.com building profile)",
          "s6_amenities": "Doorman, Exercise Room, Jacuzzi, Pool, Tennis Court, Basketball Courts",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "Not in property database.",
          "similar": [],
          "commute": [],
          "client_name": "Elle Dong"
        }
      ]
    },
    {
      "deployedAt": "2026-07-25T16:00:05.111484+00:00",
      "meta": {
        "dateLabel": "Sat, July 25",
        "agent": "Christian Daugherty"
      },
      "client": {
        "name": "Catherine Anderson",
        "fub_url": "https://jillkbiggs.followupboss.com/2/people/view/175835",
        "meta": "1 property · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Showing homes",
        "fields": [
          [
            "Budget",
            "$800,000"
          ],
          [
            "Location",
            "Hoboken, NJ"
          ]
        ],
        "snapshotLines": [
          "$800,000. Showing today (1 property)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "1032 Willow Ave #3",
          "addr2": "Hoboken, NJ 07030",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "3 BR",
          "time": "12:00 PM",
          "price": "$850,000",
          "agent": "Gerard A Mattera Jr",
          "phone": "(917) 693-1233",
          "zillow": "https://www.zillow.com/homedetails/1032-Willow-Ave-APT-3-Hoboken-NJ-07030/2126559974_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/6/HUDSON_359620.pdf",
          "flags": [],
          "s1_time": "12:00 PM",
          "s2_confirmed": "Yes — Confirmed",
          "s2_source": "Christian confirmed visually in his ShowingTime app ~11:50 AM 7/25. NOTE: overnight sub-agent falsely reported 'My Showings (0)' — automation browser's ST app was serving a stale 7/24 cache (occluded-window no-sync bug, root-caused 7/25).",
          "s3_occupancy": "Occupied — clarify: seller or tenant?",
          "s3_lb": "",
          "s3_notes": "CONFIRMED showing 12:00 PM (per Christian, ST app). Lockbox/access details not retrieved — automation browser's ShowingTime data sync is dead in the off-screen window (root-caused 7/25; fleet fix pending). LA: Gerard Mattera Jr (917) 693-1233.",
          "snap": [
            [
              "$850K",
              "Asking"
            ],
            [
              "17",
              "Days on mkt"
            ],
            [
              "$351/mo",
              "HOA/mo"
            ],
            [
              "$8,135/yr (2025)",
              "Taxes"
            ],
            [
              "992 sqft",
              "Sq ft"
            ],
            [
              "$857/sqft",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/8: $850,000 (no price changes)",
          "s5_ownership": "Bought 12/21/2020 @ $710,000. Owned ~4.6 yrs. Listed for rent 7/9/2023 at $2,775/mo (removed 7/28/2023 — assumed rented). Note: Zillow 'Show more' not expandable (viewport issue in this session); pre-2020 sale history not confirmed.",
          "s5_hoainc": "No mention",
          "s5_parking": "None",
          "s5_storage": "Storage (per common amenities: Security, Storage)",
          "s5_hvac": "A/C Wall, Baseboard, Gas",
          "s5_laundry": "In-unit washer/dryer",
          "s5_flood": "Zone X (No)",
          "s5_misc": "Intercom, Hardwood Floor, Fireplace, 10-ft ceilings, granite countertops, soaking tub; inclusions: appliances as installed; exclusions: personal property",
          "s6_age": "1901",
          "s6_units": "8 — 7 residential + 1 ground-floor commercial (taxed as 1030 Willow, per tax records)",
          "s6_amenities": "Security, Intercom, Storage",
          "s6_projects": "",
          "s6_assess": "No mention",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Catherine Anderson"
        }
      ]
    },
    {
      "deployedAt": "2026-07-25T16:00:05.111484+00:00",
      "meta": {
        "dateLabel": "Sat, July 25",
        "agent": "Christian Daugherty"
      },
      "client": {
        "name": "Mina Nedjari",
        "fub_url": "https://jillkbiggs.followupboss.com/2/people/view/217741",
        "meta": "2 properties · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Appointment set",
        "fields": [
          [
            "Budget",
            "$1,800"
          ],
          [
            "Location",
            "Jersey City Heights / Bayonne, NJ"
          ],
          [
            "Timeline",
            "0-3 months"
          ]
        ],
        "snapshotLines": [
          "$1,800. Showing today (2 properties)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "113 W 2nd St #2",
          "addr2": "Bayonne, NJ 07002",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "1 BR",
          "time": "10:00 AM",
          "price": "$190,000",
          "agent": "Lissa Ruge",
          "phone": "(551) 227-1309",
          "zillow": "https://www.zillow.com/homedetails/113-W-2nd-St-2-Bayonne-NJ-07002/2128256812_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/0/HUDSON_362054.pdf",
          "flags": [],
          "s1_time": "10:00 AM",
          "s2_confirmed": "Awaiting confirmation",
          "s2_source": "ShowingTime calendar My Showings=0 on 7/25 after hydration. Listing confirmed active in ShowingTime (ID 174684778, HCMLS 260014580). No existing appointment found for 7/25. No Auto Confirm badge. Access details tab not rendered in current session (Ionic shadow DOM). No explicit text-to-schedule signal in available data.",
          "s3_occupancy": "Occupied — clarify: seller or tenant?",
          "s3_lb": "",
          "s3_notes": "No ShowingTime appointment confirmed for 7/25. Access details not available — no confirmed appointment to pull from. Contact listing agent Lissa Ruge (551) 227-1309 to verify access before showing.",
          "snap": [
            [
              "$190K",
              "Asking"
            ],
            [
              "2",
              "Days on mkt"
            ],
            [
              "$432/mo",
              "HOA/mo"
            ],
            [
              "$3,533/yr",
              "Taxes"
            ],
            [
              "450 sqft",
              "Sq ft"
            ],
            [
              "$422/sqft",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/23: $190,000 (no price changes)",
          "s5_ownership": "No Sold event on Zillow, Redfin, or Google. Zillow shows rental listing 2/7/2011 at $900/mo (removed 5/17/2011). No prior sale confirmed — owner appears long-term holder (pre-2011). Not found after full web search.",
          "s5_hoainc": "Heat, hot water, common area maintenance, snow removal",
          "s5_parking": "1 designated spot",
          "s5_storage": "Private storage cage",
          "s5_hvac": "A/C Window; Radiators",
          "s5_laundry": "No mention",
          "s5_flood": "Zone X (No)",
          "s5_misc": "",
          "s6_age": "1950",
          "s6_units": "20 (complex spans 99-113 W 2nd St per Bayonne tax records; 2-story brick condo)",
          "s6_amenities": "None",
          "s6_projects": "",
          "s6_assess": "$305.38/mo, started Feb 2026, will last 12-18 months",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Mina Nedjari"
        },
        {
          "seq": "2",
          "addr1": "214 AVENUE A, Unit B5",
          "addr2": "Bayonne, NJ 07002",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "2 BR",
          "time": "10:00 AM",
          "price": "$269,000",
          "agent": "Christopher Piechocki",
          "phone": "(201) 978-1110",
          "zillow": "Not found — no active Zillow listing identified for '214 Avenue #A'. Address may be incomplete or unlisted. MLS step must search HCMLS directly.",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/2/HUDSON_357297.pdf",
          "flags": [],
          "s1_time": "10:00 AM",
          "s2_confirmed": "Awaiting confirmation",
          "s2_source": "ShowingTime calendar My Showings=0 on 7/25 after hydration. Listing found in ShowingTime as '214 AVENUE A, B5' (ID 173468708) — unit mismatch: appointment title shows unit A but ShowingTime/MLS show unit B5. No existing appointment for 7/25. No Auto Confirm badge. No explicit text-to-schedule signal in available data.",
          "s3_occupancy": "Occupied — clarify: seller or tenant?",
          "s3_lb": "",
          "s3_notes": "No ShowingTime appointment for 7/25. UNIT DISCREPANCY: appointment says unit A, but ShowingTime/HCMLS show unit B5 under MLS 260011832 — confirm correct unit with LA Christopher Piechocki (201) 978-1110 before arriving. Access details unknown.",
          "snap": [
            [
              "$269K",
              "Asking"
            ],
            [
              "38",
              "Days on mkt"
            ],
            [
              "$320/mo",
              "HOA/mo"
            ],
            [
              "$4,804/yr (2025)",
              "Taxes"
            ],
            [
              "602 sqft",
              "Sq ft"
            ],
            [
              "$447/sqft",
              "Per sq ft"
            ]
          ],
          "s5_history": "Not found — no active Zillow listing identified for '214 Avenue #A'. Address appears ambiguous (no specific avenue name).",
          "s5_ownership": "Not found — no Zillow listing identified. Fallback search also unsuccessful. MLS step must determine and coordinator should flag address to Christian for clarification.",
          "s5_hoainc": "No mention",
          "s5_parking": "2 tandem spots (deeded per advertising remarks; MLS features: Tandem-Shared)",
          "s5_storage": "No mention",
          "s5_hvac": "A/C Wall",
          "s5_laundry": "Building laundry room",
          "s5_flood": "Not found — no Zillow listing identified; flood zone could not be determined.",
          "s5_misc": "Hardwood floors, recessed lighting; inclusions: all major appliances; exclusions: all personal items",
          "s6_age": "Built ~1965 (Bayonne tax records; Trulia public facts show 1950 — confirm at showing)",
          "s6_units": "25 (West Bay Condominiums, 3-story brick, per tax records)",
          "s6_amenities": "None",
          "s6_projects": "",
          "s6_assess": "No mention",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Mina Nedjari"
        }
      ]
    },
    {
      "deployedAt": "2026-07-25T16:00:05.111484+00:00",
      "meta": {
        "dateLabel": "Sat, July 25",
        "agent": "Christian Daugherty"
      },
      "client": {
        "name": "Manmeet Chawla",
        "fub_url": "https://jillkbiggs.followupboss.com/2/people/view/219848",
        "meta": "1 property · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Appointment set",
        "fields": [
          [
            "Budget",
            "$1,499,000"
          ],
          [
            "Location",
            "Jersey City, NJ"
          ]
        ],
        "snapshotLines": [
          "$1,499,000. Showing today (1 property)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "73 Palisade Ave #1",
          "addr2": "Jersey City, NJ 07306",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "1 BR",
          "time": "11:30 AM",
          "price": "$296,000",
          "agent": "Samir Y Genid",
          "phone": "(973) 271-1666",
          "zillow": "https://www.zillow.com/homedetails/73-Palisade-Ave-1-Jersey-City-NJ-07306/2111066501_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/6/HUDSON_360223.pdf",
          "flags": [],
          "s1_time": "11:30 AM",
          "s2_confirmed": "Awaiting confirmation",
          "s2_source": "FUB appointment description says [Requested] status in ShowingTime, but ShowingTime calendar My Showings=0 on 7/25 after hydration. Listing confirmed active in ShowingTime (ID 174285790, 73 PALISADE AVE, 1). Discrepancy — request may have been declined, expired, or submitted under different account. No Auto Confirm badge.",
          "s3_occupancy": "Occupied — clarify: seller or tenant?",
          "s3_lb": "",
          "s3_notes": "STATUS DISCREPANCY — FUB shows [Requested] in ShowingTime but ST calendar shows 0 appointments on 7/25. Showing is at 11:30 AM — verify confirmation status immediately with listing agent Samir Genid (973) 271-1666 before arriving. Access details unknown.",
          "snap": [
            [
              "$296K",
              "Asking"
            ],
            [
              "15",
              "Days on mkt"
            ],
            [
              "$220/mo",
              "HOA/mo"
            ],
            [
              "$5,017/yr (2025)",
              "Taxes"
            ],
            [
              "438 sqft",
              "Sq ft"
            ],
            [
              "$676/sqft",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/10: $296,000 (no price changes)",
          "s5_ownership": "No Sold event on Zillow or Redfin. Redfin shows prior listing Jun 2006 at $199K (sale not confirmed in public record). Zillow shows rental 9/11/2013 at $1,100/mo (removed 9/17/2013). Owner appears long-term holder (pre-2006). Not found after full web search.",
          "s5_hoainc": "Common area maintenance",
          "s5_parking": "None",
          "s5_storage": "No mention",
          "s5_hvac": "A/C Window, Gas",
          "s5_laundry": "No mention",
          "s5_flood": "Zone X (No)",
          "s5_misc": "All furniture included (inclusions: all personal items/furniture); all appliances excluded; private backyard",
          "s6_age": "1900",
          "s6_units": "6 (association spans 73 & 75 Palisade per Hudson County tax records)",
          "s6_amenities": "Private Backyard",
          "s6_projects": "",
          "s6_assess": "No mention",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Manmeet Chawla"
        }
      ]
    },
    {
      "deployedAt": "2026-07-25T16:00:05.111484+00:00",
      "meta": {
        "dateLabel": "Sat, July 25",
        "agent": "Christian Daugherty"
      },
      "client": {
        "name": "noclient",
        "fub_url": "",
        "meta": "1 property · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Active buyer",
        "fields": [],
        "snapshotLines": [
          "Showing today (1 property)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "24 Avenue at Port Imperial #B37",
          "addr2": "West New York, NJ 07093",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "1 BR",
          "time": "1:00 PM (OH 1-3 PM)",
          "price": "$575,000",
          "agent": "Jill K Biggs ·  (Coldwell Banker / Jill Biggs Group — Christian's office)",
          "phone": "(973) 495-6038",
          "zillow": "https://www.zillow.com/homedetails/24-Avenue-At-Port-Imperial-B37-West-New-York-NJ-07093/2093437559_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/3/HUDSON_360531.pdf",
          "flags": [],
          "s1_time": "1:00 PM (OH 1-3 PM)",
          "s2_confirmed": "Yes — Confirmed (Auto Confirm)",
          "s2_source": "ShowingTime — Auto Confirm badge on listing card (ID 174404599, MLS 260013863). Vacant per MLS occupancy_hint. JBG own listing (Coldwell Banker / Jill Biggs Group). Auto Confirm = instant approval; no pre-booked appointment needed for go-and-show access.",
          "s3_occupancy": "Vacant (go-and-show)",
          "s3_lb": "",
          "s3_notes": "Own JBG / Coldwell Banker listing — Christian is the contact. Vacant, Auto Confirm, go-and-show. Lockbox/access details not retrieved from ShowingTime scheduling tab (Ionic shadow DOM not rendering in current session). Christian should know building access for own listing. Open house 7/25 & 7/26 1pm–3pm.",
          "snap": [
            [
              "$575K",
              "Asking"
            ],
            [
              "10",
              "Days on mkt"
            ],
            [
              "$597/mo",
              "HOA/mo"
            ],
            [
              "$10,500/yr (2026 — verify with city tax assessor)",
              "Taxes"
            ],
            [
              "767 sqft",
              "Sq ft"
            ],
            [
              "$750/sqft",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 5/28: $599,000 → Price cut 7/15: $575,000 (-$24K)",
          "s5_ownership": "Bought 8/31/2022 @ $525,000. Owned ~2.9 yrs. No rental history on Zillow since purchase. Note: Zillow 'Show more' not expandable (viewport issue); pre-2022 sale history not confirmed.",
          "s5_hoainc": "Parking (deeded spot #57)",
          "s5_parking": "1 Car, Covered, Garage (deeded spot #57; included in HOA)",
          "s5_storage": "Built-in shelving system in bedroom closet (per advertising)",
          "s5_hvac": "A/C Central",
          "s5_laundry": "In-unit washer/dryer",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "Private terrace, Hardwood Floor, NY/river views; inclusions: appliances and light fixtures as installed; exclusions: all personal possessions; only 1 neighbor on same floor; direct garage access from unit; quartz countertops; custom barn door in bedroom",
          "s6_age": "~2002-2004 (Hudson Club; sources conflict — likely phased completion)",
          "s6_units": "172 in this building (Hudson Club complex = 344 units across 24 & 26 Ave at Port Imperial)",
          "s6_amenities": "Doorman (24-7 concierge), Exercise Room, Jacuzzi, Pool, Tennis Court, Basketball Courts, Business Center, Children's Play Area, On-site security",
          "s6_projects": "",
          "s6_assess": "No mention",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "noclient"
        }
      ]
    },
    {
      "deployedAt": "2026-07-24T05:48:28.783616+00:00",
      "meta": {
        "dateLabel": "Fri, July 24",
        "agent": "Christian Daugherty"
      },
      "client": {
        "name": "Jessica Lynn",
        "fub_url": "https://jillkbiggs.followupboss.com/2/people/view/217633",
        "meta": "4 properties · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Showing homes",
        "fields": [
          [
            "Budget",
            "$350k max"
          ],
          [
            "Location",
            "anywhere (drives to Hackensack, nurse)"
          ],
          [
            "Home type",
            "1 bed plus condo"
          ],
          [
            "Requirements",
            "nice building; move in ready"
          ],
          [
            "Condition",
            "move in ready"
          ],
          [
            "Timeline",
            "asap before end of summer"
          ]
        ],
        "snapshotLines": [
          "$350k max. Showing today (4 properties).",
          "<b>Notes:</b> nice building; move in ready"
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "6600 Blvd E Unit 5J",
          "addr2": "West New York, NJ 07093",
          "type": "Cooperative",
          "ptype": "condo",
          "beds": "1 bed / 1 bath",
          "time": "",
          "price": "$189,000",
          "agent": "Sonia DaSilva",
          "phone": "(201) 288-4241",
          "zillow": "https://www.zillow.com/homedetails/6600-Boulevard-East-UNIT-5J-West-New-York-NJ-07093/2070933497_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/3/HUDSON_349193.pdf",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "N/A: text-scheduled",
          "s2_source": "FUB calendar says confirmed; no appointment found in ShowingTime — assumed text-scheduled",
          "s3_occupancy": "",
          "s3_lb": "",
          "s3_notes": "",
          "snap": [
            [
              "$189K",
              "Asking"
            ],
            [
              "95d",
              "Days on mkt"
            ],
            [
              "$739/mo",
              "HOA/mo"
            ],
            [
              "$378/yr",
              "Taxes"
            ],
            [
              "850 sqft",
              "Sq ft"
            ],
            [
              "$222/sqft",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 4/21/2026: $189,000",
          "s5_ownership": "Bought 4/15/2004 @ $119K (Redfin). Owned ~22 yrs. No rental history on Zillow.",
          "s5_hoainc": "Taxes, Heat, Water, Gas, Electric, Hot Water, Air Conditioner",
          "s5_parking": "None",
          "s5_storage": "None",
          "s5_hvac": "Hot Air heat; A/C wall units",
          "s5_laundry": "Common",
          "s5_flood": "Zone X (No)",
          "s5_misc": "Board approval required. Income to debt ratio 3:1 with 20% min down; 10% down = 4:1 ratio. Pets allowed.",
          "s6_age": "1959",
          "s6_units": "250",
          "s6_amenities": "Community Room, Doorman, Elevator, Exercise Room, Pool, Security, Terrace",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Jessica Lynn"
        },
        {
          "seq": "2",
          "addr1": "5 Horizon Unit 1708",
          "addr2": "Fort Lee, NJ 07024",
          "type": "Cooperative",
          "ptype": "condo",
          "beds": "1 bed / 1 bath",
          "time": "",
          "price": "$175,000",
          "agent": "Debra Jacobs",
          "phone": "(201) 803-3191",
          "zillow": "https://www.zillow.com/homedetails/5-Horizon-Rd-APT-1708-Fort-Lee-NJ-07024/2117087029_zpid/",
          "nav_addr": "",
          "disclosure": "https://njmls.mlsmatrix.com/mediaserver/GetMedia.ashx?Key=40698542&TableID=0&Type=3&Number=2&Size=0&NNF=1&RFN=Hantman+Seller+Disclosure.pdf&tstmp=0724003826&exk=e6baf23409f0554f4cbc9bd6e5853d88",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "Yes — Confirmed",
          "s2_source": "ShowingTime",
          "s3_occupancy": "Occupied — clarify: seller or tenant? (Access details not provided in ShowingTime)",
          "s3_lb": "",
          "s3_notes": "Access details not provided in ShowingTime — contact Debra Jacobs (201) 803-3191",
          "snap": [
            [
              "$175K",
              "Asking"
            ],
            [
              "10d",
              "Days on mkt"
            ],
            [
              "$1,955/mo base HOA (all util+taxes incl) + $475/mo capital assessment = $2,628/mo all-in",
              "HOA/mo"
            ],
            [
              "Included in HOA",
              "Taxes"
            ],
            [
              "1,317 sqft",
              "Sq ft"
            ],
            [
              "$133/sqft",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/13/2026: $175,000",
          "s5_ownership": "No Sold event found on Zillow/Redfin (co-op shares). Owner listed without selling in 2012 and 2013; held since before 2012 (14+ yrs). No rental history on Zillow.",
          "s5_hoainc": "Taxes, All Utilities, Cable/Internet, Parking, Amenities, Underlying Mortgage",
          "s5_parking": "Included (indoor garage +$105.60/mo for dedicated space)",
          "s5_storage": "",
          "s5_hvac": "Gas/hot air heat; central A/C multi-zone",
          "s5_laundry": "Common — basement",
          "s5_flood": "Zone X (No)",
          "s5_misc": "Board approval required. 25% down, 4:1 ITD ratio. Min gross income (cash buyer/no debt): ~$126K/yr. Board app fees: $800/$400/$500. Pets: cats & dogs OK (conditional). Offers require: POF/pre-approval, full credit report w/score, top 2 pages last 3 yrs tax returns, 1 month pay stubs, asset statements.",
          "s6_age": "1965",
          "s6_units": "Not found after web search (Horizon House complex total: 900 units across 6 buildings per Homes.com; per-building count not found)",
          "s6_amenities": "24hr Security/Doorman, Exercise Room, On-site Management (Associa 201-224-6300), Pickleball Courts, Play Area, Pool Outdoor, Shops on Premises, Tennis Ct",
          "s6_projects": "",
          "s6_assess": "$475/mo capital assessment",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Jessica Lynn"
        },
        {
          "seq": "3",
          "addr1": "6 Horizon Rd Unit 1904",
          "addr2": "Fort Lee, NJ 07024",
          "type": "Cooperative",
          "ptype": "condo",
          "beds": "1 bed / 1 bath",
          "time": "",
          "price": "$198,500",
          "agent": "Debra Jacobs",
          "phone": "(201) 803-3191",
          "zillow": "https://www.zillow.com/homedetails/6-Horizon-Rd-APT-1904-Fort-Lee-NJ-07024/2075797352_zpid/",
          "nav_addr": "",
          "disclosure": "https://njmls.mlsmatrix.com/mediaserver/GetMedia.ashx?Key=40653422&TableID=0&Type=3&Number=0&Size=0&NNF=1&RFN=JR_SD.pdf&tstmp=0724004941&exk=43544e0598d0a8373c78e4f5e8277548",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "Yes — Confirmed",
          "s2_source": "ShowingTime",
          "s3_occupancy": "Seller-occupied",
          "s3_lb": "N/A · N/A",
          "s3_notes": "Owner home or key at doorman",
          "snap": [
            [
              "$198K",
              "Asking"
            ],
            [
              "25d",
              "Days on mkt"
            ],
            [
              "$1,647/mo (all util+taxes incl) + $400/mo capital assessment = $2,244/mo all-in (incl. garage, cable)",
              "HOA/mo"
            ],
            [
              "Included in HOA",
              "Taxes"
            ],
            [
              "1,062 sqft",
              "Sq ft"
            ],
            [
              "$187/sqft",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 6/27/2026: $209,000 → Price cut 7/13/2026: $198,500 (-$10.5K)",
          "s5_ownership": "Bought 5/7/2025 @ $188K. Owned ~14 months. Prior sale: 2/25/2022 @ $90K. No rental history on Zillow.",
          "s5_hoainc": "Taxes, All Utilities (elec, gas, water), Cable, Parking, Health Club, Pool, Tennis, Underlying Mortgage",
          "s5_parking": "Indoor garage spot #182 included",
          "s5_storage": "",
          "s5_hvac": "Gas/hot air heat; Central A/C multi-zone + wall units",
          "s5_laundry": "Common — basement (coin/card)",
          "s5_flood": "Zone X (No)",
          "s5_misc": "Board approval required. 4:1 ITD ratio. All-cash buyers: min gross income ~$107K. Board app fees: $800/$400/$500. Pets: cats OK (conditional). Fully furnished turnkey (Haverty's + Crate & Barrel). Showing via ShowingTime.",
          "s6_age": "1965",
          "s6_units": "Not found after web search (Horizon House complex total: 900 units across 6 buildings per Homes.com; per-building count not found)",
          "s6_amenities": "24hr Security/Doorman, Exercise Room/Health Club, Fulltime Handyman, Hot Tub, On-site Management (Associa), Pickleball Courts, Play Area, Pool Outdoor, Shops on Premises, Super 24hrs, Tennis Ct, EV Charging in garage",
          "s6_projects": "",
          "s6_assess": "$400/mo capital assessment",
          "s6_financing": "A portion of maintenance is tax-deductible",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Jessica Lynn"
        },
        {
          "seq": "4",
          "addr1": "4 Horizon Rd Unit G18",
          "addr2": "Fort Lee, NJ 07024",
          "type": "Cooperative",
          "ptype": "condo",
          "beds": "2 bed / 2 bath",
          "time": "",
          "price": "$185,000",
          "agent": "Halley Natkin ·  (LA1; Coldwell Banker Fort Lee); Co: Debra Jacobs (201) 803-3191",
          "phone": "(917) 626-8240",
          "zillow": "https://www.zillow.com/homedetails/4-Horizon-Rd-APT-G18-Fort-Lee-NJ-07024/2098949433_zpid/",
          "nav_addr": "",
          "disclosure": "https://njmls.mlsmatrix.com/mediaserver/GetMedia.ashx?Key=40661682&TableID=0&Type=3&Number=1&Size=0&NNF=1&RFN=M0lvOUJjZmpzU3RnTXVUbjBzdzREMlJvVmQwMUN0M2N2WUM0ejFtQTV2VStTSjVkanhVWXl6RkVzbEVJS2kzeFEwSFNwclZRRktOaGVLTTc2UXJaUkE9PQ==.pdf&tstmp=0724010155&exk=4059f9ce833189e45054ca01c6875be0",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "Yes — Confirmed",
          "s2_source": "ShowingTime",
          "s3_occupancy": "Vacant (go-and-show; virtually staged — access details not provided in ShowingTime)",
          "s3_lb": "",
          "s3_notes": "Access details not provided in ShowingTime — contact Halley Natkin (917) 626-8240 or Debra Jacobs (201) 803-3191",
          "snap": [
            [
              "$185K",
              "Asking"
            ],
            [
              "22d",
              "Days on mkt"
            ],
            [
              "$2,084/mo (listed base); $2,761.52/mo all-in",
              "HOA/mo"
            ],
            [
              "Included in HOA",
              "Taxes"
            ],
            [
              "1,317 sqft",
              "Sq ft"
            ],
            [
              "$141/sqft",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/1/2026: $185,000",
          "s5_ownership": "Bought 9/28/2018 @ $140K (Trulia). Owned ~8 yrs. No rental history on Zillow.",
          "s5_hoainc": "Taxes, All Utilities (elec/gas/heat/HW), Cable/Int, Assessments, Underlying Mortgage, Parking, Amenities",
          "s5_parking": "Included — deck parking spot #14 (premier)",
          "s5_storage": "",
          "s5_hvac": "All utilities included in HOA (electric/gas/heat/hot water)",
          "s5_laundry": "Common — Coin/Card, Basement",
          "s5_flood": "Zone X (No)",
          "s5_misc": "Board: 25% down, 4:1 ITD. All-cash purchase (no other debt) requires min $132K gross income. Board fees: $800 APP, $400 M/I, $500 Dep. Pets conditional. 810 shares. Possession: 61-90 days. Subject to Board Approval.",
          "s6_age": "1965",
          "s6_units": "Not found after web search (Horizon House complex total: 900 units across 6 buildings per Homes.com; per-building count not found)",
          "s6_amenities": "24hr Doorman, Elevator (building), Exercise Room, Fulltime Handyman, On-site Management, Pickleball Ct, Play Area, Pool Outdoor, Recycling, Shops on Premises, Super 24hr, Tennis Ct",
          "s6_projects": "",
          "s6_assess": "$506.25/mo capital assessment (included in all-in total)",
          "s6_financing": "25% down; 4:1 ITD",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Jessica Lynn"
        }
      ]
    }
  ]
};
