/* ============================================================
   FIELD COMPANION — SHOWING DATA   (auto-generated)
   ------------------------------------------------------------
   Generated by build_field_companion.py from the same prepped
   showing dicts that build the packet. This is the ONLY file
   the showing-prep workflow overwrites; the app shell
   (field_companion.html) is never touched per showing.

   DO NOT hand-edit — rerun the generator instead.
   ============================================================ */
window.FC_DATA = {
  "meta": {
    "dateLabel": "Sat, July 11",
    "agent": "Christian Daugherty",
    "deployedAt": "2026-07-11T04:27:52.160003+00:00"
  },
  "appointments": [
    {
      "date": "Sat, July 11",
      "client": {
        "name": "Christian Merkle",
        "fub_url": "https://jillkbiggs.followupboss.com/2/people/view/217538",
        "meta": "3 properties · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Appointment set",
        "fields": [
          [
            "Budget",
            "$296,000"
          ],
          [
            "Location",
            "Jersey City / Hoboken / Bergen County / Essex County"
          ],
          [
            "Home type",
            "Condo"
          ],
          [
            "Requirements",
            "1-2 BR, garage preferred"
          ]
        ],
        "snapshotLines": [
          "$296,000. Showing today (3 properties).",
          "<b>Notes:</b> 1-2 BR, garage preferred"
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "209 Webster Ave #3R",
          "addr2": "Jersey City, NJ 07307",
          "type": "Condo",
          "ptype": "condo",
          "beds": "1 BR · 1 BA",
          "time": "11:00 AM",
          "price": "$335,000",
          "agent": "Judy Chin",
          "phone": "973-723-2005",
          "zillow": "https://www.zillow.com/homedetails/209-Webster-Ave-APT-3R-Jersey-City-NJ-07307/2134432122_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/1/HUDSON_357588.pdf",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "N/A: text-scheduled",
          "s2_source": "ShowingTime: 'Not Accepting Online Appointment Requests Through ShowingTime — This listing is not accepting online appointment requests through ShowingTime. See Hudson County MLS listing page for scheduling instructions.'",
          "s3_occupancy": "Occupied — clarify: seller or tenant?",
          "s3_lb": "",
          "s3_notes": "",
          "snap": [
            [
              "$335K",
              "Asking"
            ],
            [
              "23d",
              "Days on mkt"
            ],
            [
              "$335",
              "HOA/mo"
            ],
            [
              "$5,625",
              "Taxes"
            ],
            [
              "593 sf",
              "Sq ft"
            ],
            [
              "$565",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 6/18/2026: $335K (no changes)",
          "s5_ownership": "Bought 6/29/2016 @ $200K. Owned ~10 yrs. No rental history on Zillow.",
          "s5_hoainc": "Water",
          "s5_parking": "None",
          "s5_storage": "None",
          "s5_hvac": "Central A/C + central heat (type not specified — verify at showing)",
          "s5_laundry": "In-unit washer/dryer",
          "s5_flood": "Zone X (No)",
          "s5_misc": "",
          "s6_age": "Built 1890",
          "s6_units": "6 units",
          "s6_amenities": "Shared backyard",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Christian Merkle"
        },
        {
          "seq": "2",
          "addr1": "50 Reservoir Ave #B1",
          "addr2": "Jersey City, NJ 07307",
          "type": "Condo",
          "ptype": "condo",
          "beds": "2 BR · 1 BA",
          "time": "11:00 AM",
          "price": "$374,900",
          "agent": "Andrew Botticelli",
          "phone": "908-433-7999",
          "zillow": "https://www.zillow.com/homedetails/50-Reservoir-Ave-APT-B1-Jersey-City-NJ-07307/2078391055_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/0/HUDSON_347038.pdf",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "Yes — Confirmed (Auto Confirm)",
          "s2_source": "ShowingTime",
          "s3_occupancy": "Vacant (go-and-show)",
          "s3_lb": "Combination · Code: Lockbox code: 4590 · B1's Webster Ave Courtyard entrance, stair landing",
          "s3_notes": "",
          "snap": [
            [
              "$375K",
              "Asking"
            ],
            [
              "99d",
              "Days on mkt"
            ],
            [
              "$954",
              "HOA/mo"
            ],
            [
              "$7,269",
              "Taxes"
            ],
            [
              "986 sf",
              "Sq ft"
            ],
            [
              "$380",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 5/11/2023: $399.9K → cut to $329.9K (-$70K), removed 12/2023. Re-listed 4/3/2026: $374.9K (no changes). Actual DOM: ~1,155 days (on market since 5/11/2023)",
          "s5_ownership": "Not found after web search — no Sold event in Zillow or Redfin. Unit listed for rent starting 8/4/2020 @ $1,550/mo (multiple rental cycles 2020–2025); purchase pre-dates syndication.",
          "s5_hoainc": "Heat, Water, Hot Water",
          "s5_parking": "None",
          "s5_storage": "None",
          "s5_hvac": "Window A/C; steam heat (included in HOA)",
          "s5_laundry": "Common laundry room",
          "s5_flood": "Zone X (No)",
          "s5_misc": "",
          "s6_age": "Built 1924",
          "s6_units": "32 units",
          "s6_amenities": "Elevator",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Christian Merkle"
        },
        {
          "seq": "3",
          "addr1": "73 Palisade Ave #1",
          "addr2": "Jersey City, NJ 07306",
          "type": "Condo",
          "ptype": "condo",
          "beds": "1 BR · 1 BA",
          "time": "11:00 AM",
          "price": "$296,000",
          "agent": "Samir Y. Genid",
          "phone": "973-271-1666",
          "zillow": "https://www.zillow.com/homedetails/73-Palisade-Ave-1-Jersey-City-NJ-07306/2111066501_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/6/HUDSON_360223.pdf",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "Yes — Confirmed",
          "s2_source": "ShowingTime",
          "s3_occupancy": "Tenant-occupied",
          "s3_lb": "Combination · Code: Door code: 3693",
          "s3_notes": "Backyard not directly accessible from apartment — go through common area. Issues: call landlord Erik (908)361-7000.",
          "snap": [
            [
              "$296K",
              "Asking"
            ],
            [
              "1d",
              "Days on mkt"
            ],
            [
              "$220",
              "HOA/mo"
            ],
            [
              "438 sf",
              "Sq ft"
            ],
            [
              "$676",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/10/2026: $296K (no changes)",
          "s5_ownership": "Bought 10/25/2024 @ $299K (per public records/Google). Owned ~1.7 yrs. No rental history on Zillow under current ownership.",
          "s5_hoainc": "Common area maintenance (per advertising remarks; MLS fee-includes field blank)",
          "s5_parking": "None",
          "s5_storage": "None",
          "s5_hvac": "Window A/C; gas heat (type not specified — verify at showing)",
          "s5_laundry": "",
          "s5_flood": "Zone X (No)",
          "s5_misc": "All furniture included in sale.",
          "s6_age": "Built 1900",
          "s6_units": "3 units",
          "s6_amenities": "None",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Christian Merkle"
        }
      ]
    },
    {
      "date": "Sat, July 11",
      "client": {
        "name": "Open House",
        "fub_url": "",
        "meta": "1 property · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Active buyer",
        "fields": [],
        "snapshotLines": [
          "Showing today (1 property)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "339 Palisade Ave #C",
          "addr2": "Jersey City, NJ 07307",
          "type": "Condo",
          "ptype": "condo",
          "beds": "3 BR · 3 BA",
          "time": "1:00 PM",
          "price": "$875,000",
          "agent": "Phoebe",
          "phone": "201-214-5356",
          "zillow": "https://www.zillow.com/homedetails/339-Palisade-Ave-C-Jersey-City-NJ-07307/463736480_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/4/HUDSON_359584.pdf",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "N/A: text-scheduled",
          "s2_source": "Open House — Christian is hosting; no buyer showing appointment in ShowingTime. Listing shows Auto Confirm on ST (MLS# 260013284).",
          "s3_occupancy": "Occupied — clarify: seller or tenant?",
          "s3_lb": "",
          "s3_notes": "",
          "snap": [
            [
              "$875K",
              "Asking"
            ],
            [
              "3d",
              "Days on mkt"
            ],
            [
              "$403",
              "HOA/mo"
            ],
            [
              "$19,200",
              "Taxes"
            ],
            [
              "1,430 sf",
              "Sq ft"
            ],
            [
              "$612",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/8/2026: $875K (no changes)",
          "s5_ownership": "New construction (2020s). No prior sale record for this condo unit as a distinct parcel. Underlying lot sold late 2021 for ~$245K before condominium conversion (per public records).",
          "s5_hoainc": "Water",
          "s5_parking": "None",
          "s5_storage": "None",
          "s5_hvac": "Central A/C; gas forced hot air",
          "s5_laundry": "In-unit washer/dryer",
          "s5_flood": "Zone X (No)",
          "s5_misc": "1 car reserved parking spot available to rent from sellers (6 months; ask LA for address). 1% rate buy-down offered with preferred lender.",
          "s6_age": "Built 2022",
          "s6_units": "3 units (labeled A, B, C)",
          "s6_amenities": "None",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Open House"
        }
      ]
    }
  ],
  "client": {
    "name": "Christian Merkle",
    "fub_url": "https://jillkbiggs.followupboss.com/2/people/view/217538",
    "meta": "3 properties · Buyer · Christian Daugherty, Jill Biggs Group",
    "stage": "Appointment set",
    "fields": [
      [
        "Budget",
        "$296,000"
      ],
      [
        "Location",
        "Jersey City / Hoboken / Bergen County / Essex County"
      ],
      [
        "Home type",
        "Condo"
      ],
      [
        "Requirements",
        "1-2 BR, garage preferred"
      ]
    ],
    "snapshotLines": [
      "$296,000. Showing today (3 properties).",
      "<b>Notes:</b> 1-2 BR, garage preferred"
    ]
  },
  "props": [
    {
      "seq": "1",
      "addr1": "209 Webster Ave #3R",
      "addr2": "Jersey City, NJ 07307",
      "type": "Condo",
      "ptype": "condo",
      "beds": "1 BR · 1 BA",
      "time": "11:00 AM",
      "price": "$335,000",
      "agent": "Judy Chin",
      "phone": "973-723-2005",
      "zillow": "https://www.zillow.com/homedetails/209-Webster-Ave-APT-3R-Jersey-City-NJ-07307/2134432122_zpid/",
      "nav_addr": "",
      "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/1/HUDSON_357588.pdf",
      "flags": [],
      "s1_time": "",
      "s2_confirmed": "N/A: text-scheduled",
      "s2_source": "ShowingTime: 'Not Accepting Online Appointment Requests Through ShowingTime — This listing is not accepting online appointment requests through ShowingTime. See Hudson County MLS listing page for scheduling instructions.'",
      "s3_occupancy": "Occupied — clarify: seller or tenant?",
      "s3_lb": "",
      "s3_notes": "",
      "snap": [
        [
          "$335K",
          "Asking"
        ],
        [
          "23d",
          "Days on mkt"
        ],
        [
          "$335",
          "HOA/mo"
        ],
        [
          "$5,625",
          "Taxes"
        ],
        [
          "593 sf",
          "Sq ft"
        ],
        [
          "$565",
          "Per sq ft"
        ]
      ],
      "s5_history": "Listed 6/18/2026: $335K (no changes)",
      "s5_ownership": "Bought 6/29/2016 @ $200K. Owned ~10 yrs. No rental history on Zillow.",
      "s5_hoainc": "Water",
      "s5_parking": "None",
      "s5_storage": "None",
      "s5_hvac": "Central A/C + central heat (type not specified — verify at showing)",
      "s5_laundry": "In-unit washer/dryer",
      "s5_flood": "Zone X (No)",
      "s5_misc": "",
      "s6_age": "Built 1890",
      "s6_units": "6 units",
      "s6_amenities": "Shared backyard",
      "s6_projects": "",
      "s6_assess": "",
      "s6_financing": "",
      "s6_key": "",
      "similar": [],
      "commute": [],
      "client_name": "Christian Merkle"
    },
    {
      "seq": "2",
      "addr1": "50 Reservoir Ave #B1",
      "addr2": "Jersey City, NJ 07307",
      "type": "Condo",
      "ptype": "condo",
      "beds": "2 BR · 1 BA",
      "time": "11:00 AM",
      "price": "$374,900",
      "agent": "Andrew Botticelli",
      "phone": "908-433-7999",
      "zillow": "https://www.zillow.com/homedetails/50-Reservoir-Ave-APT-B1-Jersey-City-NJ-07307/2078391055_zpid/",
      "nav_addr": "",
      "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/0/HUDSON_347038.pdf",
      "flags": [],
      "s1_time": "",
      "s2_confirmed": "Yes — Confirmed (Auto Confirm)",
      "s2_source": "ShowingTime",
      "s3_occupancy": "Vacant (go-and-show)",
      "s3_lb": "Combination · Code: Lockbox code: 4590 · B1's Webster Ave Courtyard entrance, stair landing",
      "s3_notes": "",
      "snap": [
        [
          "$375K",
          "Asking"
        ],
        [
          "99d",
          "Days on mkt"
        ],
        [
          "$954",
          "HOA/mo"
        ],
        [
          "$7,269",
          "Taxes"
        ],
        [
          "986 sf",
          "Sq ft"
        ],
        [
          "$380",
          "Per sq ft"
        ]
      ],
      "s5_history": "Listed 5/11/2023: $399.9K → cut to $329.9K (-$70K), removed 12/2023. Re-listed 4/3/2026: $374.9K (no changes). Actual DOM: ~1,155 days (on market since 5/11/2023)",
      "s5_ownership": "Not found after web search — no Sold event in Zillow or Redfin. Unit listed for rent starting 8/4/2020 @ $1,550/mo (multiple rental cycles 2020–2025); purchase pre-dates syndication.",
      "s5_hoainc": "Heat, Water, Hot Water",
      "s5_parking": "None",
      "s5_storage": "None",
      "s5_hvac": "Window A/C; steam heat (included in HOA)",
      "s5_laundry": "Common laundry room",
      "s5_flood": "Zone X (No)",
      "s5_misc": "",
      "s6_age": "Built 1924",
      "s6_units": "32 units",
      "s6_amenities": "Elevator",
      "s6_projects": "",
      "s6_assess": "",
      "s6_financing": "",
      "s6_key": "",
      "similar": [],
      "commute": [],
      "client_name": "Christian Merkle"
    },
    {
      "seq": "3",
      "addr1": "73 Palisade Ave #1",
      "addr2": "Jersey City, NJ 07306",
      "type": "Condo",
      "ptype": "condo",
      "beds": "1 BR · 1 BA",
      "time": "11:00 AM",
      "price": "$296,000",
      "agent": "Samir Y. Genid",
      "phone": "973-271-1666",
      "zillow": "https://www.zillow.com/homedetails/73-Palisade-Ave-1-Jersey-City-NJ-07306/2111066501_zpid/",
      "nav_addr": "",
      "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/6/HUDSON_360223.pdf",
      "flags": [],
      "s1_time": "",
      "s2_confirmed": "Yes — Confirmed",
      "s2_source": "ShowingTime",
      "s3_occupancy": "Tenant-occupied",
      "s3_lb": "Combination · Code: Door code: 3693",
      "s3_notes": "Backyard not directly accessible from apartment — go through common area. Issues: call landlord Erik (908)361-7000.",
      "snap": [
        [
          "$296K",
          "Asking"
        ],
        [
          "1d",
          "Days on mkt"
        ],
        [
          "$220",
          "HOA/mo"
        ],
        [
          "438 sf",
          "Sq ft"
        ],
        [
          "$676",
          "Per sq ft"
        ]
      ],
      "s5_history": "Listed 7/10/2026: $296K (no changes)",
      "s5_ownership": "Bought 10/25/2024 @ $299K (per public records/Google). Owned ~1.7 yrs. No rental history on Zillow under current ownership.",
      "s5_hoainc": "Common area maintenance (per advertising remarks; MLS fee-includes field blank)",
      "s5_parking": "None",
      "s5_storage": "None",
      "s5_hvac": "Window A/C; gas heat (type not specified — verify at showing)",
      "s5_laundry": "",
      "s5_flood": "Zone X (No)",
      "s5_misc": "All furniture included in sale.",
      "s6_age": "Built 1900",
      "s6_units": "3 units",
      "s6_amenities": "None",
      "s6_projects": "",
      "s6_assess": "",
      "s6_financing": "",
      "s6_key": "",
      "similar": [],
      "commute": [],
      "client_name": "Christian Merkle"
    }
  ],
  "history": [
    {
      "deployedAt": "2026-07-10T18:33:13.043070+00:00",
      "meta": {
        "dateLabel": "Fri, July 10",
        "agent": "Christian Daugherty"
      },
      "client": {
        "name": "Olca Ozekin",
        "fub_url": "https://jillkbiggs.followupboss.com/2/people/view/149794",
        "meta": "5 properties · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Showing homes",
        "fields": [
          [
            "Budget",
            "$599,000"
          ]
        ],
        "snapshotLines": [
          "$599,000. Showing today (5 properties)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "123 The Promenade #123",
          "addr2": "Edgewater, NJ 07020",
          "type": "Condo",
          "ptype": "condo",
          "beds": "2 BR · 2 BA",
          "time": "",
          "price": "$620,000",
          "agent": "Sophie S. Kang",
          "phone": "(201) 281-5593",
          "zillow": "https://www.zillow.com/homedetails/123-The-Promenade-UNIT-123-Edgewater-NJ-07020/2068716553_zpid/",
          "nav_addr": "",
          "disclosure": "https://njmls.mlsmatrix.com/mediaserver/GetMedia.ashx?Key=40721148&TableID=0&Type=3&Number=0&Size=0&NNF=1&RFN=Seller+Disclosurepdf_123.pdf&tstmp=0710141519&exk=38d38b8024cc0b88f32dd5a4320c4018",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "Yes — Confirmed (provided by Christian — appointment already booked)",
          "s2_source": "Provided by Christian",
          "s3_occupancy": "Not stated",
          "s3_lb": "N/A — meeting listing agent · N/A — meeting listing agent",
          "s3_notes": "meeting listing agent",
          "snap": [
            [
              "$620K",
              "Asking"
            ],
            [
              "1d",
              "Days on mkt"
            ],
            [
              "$1,101",
              "HOA/mo"
            ],
            [
              "$9,173",
              "Taxes"
            ],
            [
              "1,456 sf",
              "Sq ft"
            ],
            [
              "$426",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/6/26: $620K",
          "s5_ownership": "Bought 11/19/21 @ $530K. Owned ~4.6 yrs. No rental history on Zillow.",
          "s5_hoainc": "Water",
          "s5_parking": "1 indoor garage space (Space #12, included)",
          "s5_storage": "None",
          "s5_hvac": "Gas forced hot air; Central AC",
          "s5_laundry": "In-unit",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "Possession: 31–60 days after closing. Board Assoc additional charge at closing: 2x HOA fee + $1,000 + $400 + $1,000 (refundable).",
          "s6_age": "Built 2003 (The Promenade Condominiums building profile — newjerseyproper.com; not on MLS sheet)",
          "s6_units": "161 condominium units (3-story low-rise waterfront community — newjerseyproper.com building profile)",
          "s6_amenities": "24-hour security, exercise room, gated community",
          "s6_projects": "",
          "s6_assess": "$380.02 (assessment, per listing). Municipal assessments: none known.",
          "s6_financing": "",
          "s6_key": "(observed 2026-06-11) Go to guard shack for the keys then park next to the abandoned movie theater parking lot and enter through the green gate.",
          "similar": [],
          "commute": [],
          "client_name": "Olca Ozekin"
        },
        {
          "seq": "2",
          "addr1": "337 The Promenade #337",
          "addr2": "Edgewater, NJ 07020",
          "type": "Condo",
          "ptype": "condo",
          "beds": "2 BR · 2 BA",
          "time": "",
          "price": "$629,000",
          "agent": "Hyunju Lee",
          "phone": "(201) 317-1719",
          "zillow": "https://www.zillow.com/homedetails/337-The-Promenade-337-Edgewater-NJ-07020/461185374_zpid/",
          "nav_addr": "",
          "disclosure": "",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "Yes — Confirmed (provided by Christian — appointment already booked)",
          "s2_source": "Provided by Christian",
          "s3_occupancy": "Not stated",
          "s3_lb": "Supra · Not stated",
          "s3_notes": "Supra with guard shack",
          "snap": [
            [
              "$629K",
              "Asking"
            ],
            [
              "42d",
              "Days on mkt"
            ],
            [
              "$1,100",
              "HOA/mo"
            ],
            [
              "$9,820",
              "Taxes"
            ],
            [
              "1,506 sf",
              "Sq ft"
            ],
            [
              "$418",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 3/20/26: $629K — relisted 5/29/26 (no change). Actual DOM: 112 days (on market since 3/20/26)",
          "s5_ownership": "No prior sale on record (built 2003; checked Zillow, Redfin, Homes.com public records — no Sold event found). Rented ~$3.3–3.4K/mo (Nov 2021).",
          "s5_hoainc": "Maintenance - Common Area",
          "s5_parking": "1 indoor covered garage space (included)",
          "s5_storage": "None",
          "s5_hvac": "Gas forced hot air; Central AC",
          "s5_laundry": "In-unit",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "Possession: 0–30 days after closing. Board Assoc additional charge — see remarks (not specified in listing).",
          "s6_age": "Built 2003 (The Promenade Condominiums building profile — newjerseyproper.com; not on MLS sheet)",
          "s6_units": "161 condominium units (3-story low-rise waterfront community — newjerseyproper.com building profile)",
          "s6_amenities": "24-hour doorman/security, exercise room, community room, gated community, full-time handyman",
          "s6_projects": "",
          "s6_assess": "Municipal assessment on file — amount not specified in listing.",
          "s6_financing": "",
          "s6_key": "(observed 2026-06-11) Go to guard shack for the keys then park next to the abandoned movie theater parking lot and enter through the green gate.",
          "similar": [],
          "commute": [],
          "client_name": "Olca Ozekin"
        },
        {
          "seq": "3",
          "addr1": "6407 City Pl #6407",
          "addr2": "Edgewater, NJ 07020",
          "type": "Condo",
          "ptype": "condo",
          "beds": "1 BR · 1 BA",
          "time": "",
          "price": "$535,000",
          "agent": "Daniel Malloy",
          "phone": "(201) 615-8303",
          "zillow": "https://www.zillow.com/homedetails/6407-City-Pl-6407-Edgewater-NJ-07020/461564984_zpid/",
          "nav_addr": "",
          "disclosure": "https://njmls.mlsmatrix.com/mediaserver/GetMedia.ashx?Key=40210176&TableID=0&Type=3&Number=0&Size=0&NNF=1&RFN=6407+city+place+olga+sellers+disclosure.pdf&tstmp=0710141743&exk=e161a6ceef37808e78acdb9766cbcb4e",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "Yes — Confirmed (provided by Christian — appointment already booked)",
          "s2_source": "Provided by Christian",
          "s3_occupancy": "Not stated",
          "s3_lb": "Master lockbox · Code: Front door code: 9694 · 4th floor, front door",
          "s3_notes": "4th floor lock box master lockbox in front door 9694",
          "snap": [
            [
              "$535K",
              "Asking"
            ],
            [
              "93d",
              "Days on mkt"
            ],
            [
              "$642",
              "HOA/mo"
            ],
            [
              "$6,902",
              "Taxes"
            ]
          ],
          "s5_history": "Listed 4/8/26: $569K → Price cut 5/12/26: $535K (-$34K)",
          "s5_ownership": "Bought 1/25/10 @ $450K (public records, via Redfin). Owned ~16.5 yrs. No rental history found.",
          "s5_hoainc": "Not listed on MLS.",
          "s5_parking": "2 indoor garage spaces (included)",
          "s5_storage": "None",
          "s5_hvac": "Electric heat pump; Central AC",
          "s5_laundry": "In-unit",
          "s5_flood": "Zone X (No)",
          "s5_misc": "Possession: 0–30 days after closing. Board Assoc additional charge: move-in fee applies (amount not specified).",
          "s6_age": "Built 2005 (Riverview at City Place — Homes.com/public-records building profile, corroborated by listing description naming 'Building 6'; not on MLS sheet)",
          "s6_units": "130 units, 6 stories (Riverview at City Place — Buildings 5 and 6 combined; Homes.com/public-records building profile)",
          "s6_amenities": "24-hour doorman, common area",
          "s6_projects": "",
          "s6_assess": "Municipal assessments: none known.",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Olca Ozekin"
        },
        {
          "seq": "4",
          "addr1": "5311 City Pl",
          "addr2": "Edgewater, NJ 07020",
          "type": "Condo",
          "ptype": "condo",
          "beds": "2 BR · 2 BA",
          "time": "",
          "price": "$649,000",
          "agent": "Stephen Braconi",
          "phone": "(551) 804-8364",
          "zillow": "https://www.zillow.com/homedetails/5311-City-Pl-Edgewater-NJ-07020/64759303_zpid/",
          "nav_addr": "",
          "disclosure": "",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "Yes — Confirmed (provided by Christian — appointment already booked)",
          "s2_source": "Provided by Christian",
          "s3_occupancy": "Not stated",
          "s3_lb": "Supra · On unit door",
          "s3_notes": "Supra on door",
          "snap": [
            [
              "$649K",
              "Asking"
            ],
            [
              "179d",
              "Days on mkt"
            ],
            [
              "$984",
              "HOA/mo"
            ],
            [
              "$9,443",
              "Taxes"
            ],
            [
              "1,383 sf",
              "Sq ft"
            ],
            [
              "$469",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 8/15/25: $699K → Cut 10/15/25: $679K (-$20K) → Relisted 1/12/26: $679K → Cut 2/28/26: $649K (-$30K). Actual DOM: 329 days (on market since 8/15/25)",
          "s5_ownership": "Bought 2/23/05 @ $616,131. Owned ~21.4 yrs. No rental history on Zillow.",
          "s5_hoainc": "Not listed on MLS.",
          "s5_parking": "2 deck garage spaces (included)",
          "s5_storage": "None",
          "s5_hvac": "Electric forced hot air; Wall A/C units",
          "s5_laundry": "In-unit",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "Possession: 0–30 days after closing.",
          "s6_age": "Built 2005 (Riverview at City Place — Homes.com/public-records building profile; not on MLS sheet)",
          "s6_units": "130 units, 6 stories (Riverview at City Place — Buildings 5 and 6 combined; Homes.com/public-records building profile)",
          "s6_amenities": "Doorman, elevator(s), common area, on-site shops",
          "s6_projects": "",
          "s6_assess": "Municipal assessments: none known. Board Assoc additional charge: TBD — amount not yet determined.",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Olca Ozekin"
        },
        {
          "seq": "5",
          "addr1": "2305 City Pl",
          "addr2": "Edgewater, NJ 07020",
          "type": "Condo",
          "ptype": "condo",
          "beds": "2 BR · 1.5 BA",
          "time": "",
          "price": "$529,000",
          "agent": "Joachim Horvitz",
          "phone": "(201) 892-9035",
          "zillow": "https://www.zillow.com/homedetails/2305-City-Pl-Edgewater-NJ-07020/82652057_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/8/HUDSON_356064.pdf",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "Yes — Confirmed (provided by Christian — appointment already booked)",
          "s2_source": "Provided by Christian",
          "s3_occupancy": "Not stated",
          "s3_lb": "N/A — concierge access · Code: Building entry code: 9035 · Building 3 concierge lobby, elevator to 3rd floor",
          "s3_notes": "Bring business card for concierge. Enter through concierge lobby (building 3). Elevator for 3rd floor. Code is 9035. Please press lock when you leave.",
          "snap": [
            [
              "$529K",
              "Asking"
            ],
            [
              "31d",
              "Days on mkt"
            ],
            [
              "$783",
              "HOA/mo"
            ],
            [
              "$6,372",
              "Taxes"
            ],
            [
              "1,128 sf",
              "Sq ft"
            ],
            [
              "$469",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 6/26/24: $585K → Cut 9/4/24: $559.9K (-$25.1K) → Cut 5/12/26: $529.9K (-$30K) → Cut 6/9/26: $529K (-$900). Actual DOM: 744 days (on market since 6/26/24)",
          "s5_ownership": "Bought 11/9/15 @ $472,500. Owned ~10.7 yrs. No rental history under current ownership (a rental listing from 10/2015 predates the sale).",
          "s5_hoainc": "Parking",
          "s5_parking": "2 cars — attached, covered garage (included)",
          "s5_storage": "None",
          "s5_hvac": "Heat pump; Wall A/C units",
          "s5_laundry": "In-unit",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "",
          "s6_age": "Built 2005 (The Peninsula at City Place — Homes.com building profile / multiple unit public records; MLS broker remarks confirm the unit is in 'Building 2, Floor 3'; not on MLS Year-Built field)",
          "s6_units": "~201 units, 5 stories (The Peninsula at City Place, Buildings 2 and 3 combined, above ground-floor retail — Homes.com building profile)",
          "s6_amenities": "Community room, doorman, elevator, on-site shops",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Olca Ozekin"
        }
      ]
    },
    {
      "deployedAt": "2026-07-10T03:59:44.181364+00:00",
      "meta": {
        "dateLabel": "Thu, July 9",
        "agent": "Christian Daugherty"
      },
      "client": {
        "name": "Olca Ozekin",
        "fub_url": "https://jillkbiggs.followupboss.com/2/people/view/149794",
        "meta": "1 property · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Showing homes",
        "fields": [
          [
            "Budget",
            "$599,000"
          ],
          [
            "Home type",
            "Buyer"
          ]
        ],
        "snapshotLines": [
          "$599,000. Showing today (1 property)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "337 The Promenade",
          "addr2": "Edgewater, NJ 07020",
          "type": "Condo",
          "ptype": "condo",
          "beds": "2 BR · 2 BA",
          "time": "6:00 PM",
          "price": "$629,000",
          "agent": "Hyunju Lee",
          "phone": "201-317-1719",
          "zillow": "https://www.zillow.com/homedetails/337-The-Promenade-337-Edgewater-NJ-07020/461185374_zpid/",
          "nav_addr": "195 River Rd",
          "disclosure": "",
          "flags": [],
          "s1_time": "6:00 PM",
          "s2_confirmed": "Awaiting confirmation",
          "s2_source": "ShowingTime — listing accepts online appointments but none booked yet for 7/9 at 6 PM. 6 PM slot was open on ShowingTime availability calendar. Appointment needs to be scheduled.",
          "s3_occupancy": "Occupied — clarify: seller or tenant?",
          "s3_lb": "",
          "s3_notes": "No ShowingTime appointment booked yet — schedule before showing. Per MLS: go to guard shack for keys, park next to abandoned movie theater parking lot, enter through green gate.",
          "snap": [
            [
              "$629K",
              "Asking"
            ],
            [
              "39d",
              "Days on mkt"
            ],
            [
              "$1,100/mo",
              "HOA/mo"
            ],
            [
              "1,506 sf",
              "Sq ft"
            ],
            [
              "$418/sf",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 3/20: $629K (NJMLS #26008971) → Relisted 5/29: $629K (NJMLS #26019864, same price). Actual DOM: 110 days (on market since 3/20/2026)",
          "s5_ownership": "No prior sale found in Zillow or Redfin public records — only listing events (3/20/2026 and 5/29/2026) appear in history. Redfin public record fields are blank (no APN, no year built in records). Built 2003 per Redfin. Current ownership duration unknown — no prior Sold event in any public source.",
          "s5_hoainc": "",
          "s5_parking": "1 covered space",
          "s5_storage": "None",
          "s5_hvac": "Central A/C; Gas/hot air heat",
          "s5_laundry": "In unit (W/D included)",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "",
          "s6_age": "2003",
          "s6_units": "161",
          "s6_amenities": "Elevator, Gated community, 24hr security, Exercise room, Full-time handyman, Common area",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "(observed 2026-06-11) Go to guard shack for the keys then park next to the abandoned movie theater parking lot and enter through the green gate.",
          "similar": [],
          "commute": [],
          "client_name": "Olca Ozekin"
        }
      ]
    },
    {
      "deployedAt": "2026-07-10T03:59:44.181364+00:00",
      "meta": {
        "dateLabel": "Thu, July 9",
        "agent": "Christian Daugherty"
      },
      "client": {
        "name": "Jennifer",
        "fub_url": "https://jillkbiggs.followupboss.com/2/people/view/24219",
        "meta": "1 property · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Appointment set",
        "fields": [
          [
            "Budget",
            "$2,650"
          ]
        ],
        "snapshotLines": [
          "$2,650. Showing today (1 property)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "380 Mountain Rd #805",
          "addr2": "Union City, NJ 07087",
          "type": "Co-op",
          "ptype": "condo",
          "beds": "1 BR · 1 BA",
          "time": "6:00 PM",
          "price": "$289,000",
          "agent": "Ashi",
          "phone": "917-627-2104",
          "zillow": "https://www.zillow.com/homedetails/380-Mountain-Rd-805-Union-City-NJ-07087/460473505_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/3/HUDSON_341226.pdf",
          "flags": [],
          "s1_time": "6:00 PM",
          "s2_confirmed": "N/A: text-scheduled",
          "s2_source": "ShowingTime: 'Not Accepting Online Appointment Requests Through ShowingTime — see Hudson County MLS listing page for scheduling instructions.' Contact listing agent Ashi at 917-627-2104 to schedule.",
          "s3_occupancy": "Occupied — clarify: seller or tenant?",
          "s3_lb": "N/A · N/A",
          "s3_notes": "Text-scheduled — contact Ashi at 917-627-2104 to book. Building has 24hr doorman/concierge; keys/access likely handled at front desk.",
          "snap": [
            [
              "$289K",
              "Asking"
            ],
            [
              "73d",
              "Days on mkt"
            ],
            [
              "$1,300/mo",
              "HOA/mo"
            ],
            [
              "Incl. in HOA",
              "Taxes"
            ],
            [
              "940 sf",
              "Sq ft"
            ],
            [
              "$307/sf",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 2/13: $289K → Removed 3/18 → Relisted 5/22: $289K (same price). Actual DOM: 145 days (on market since 2/13/2026)",
          "s5_ownership": "Co-op — no prior sale in public deed records (co-op stock shares not recorded as deeds; no Sold events in Zillow price history after full expansion). No rental history on Zillow.",
          "s5_hoainc": "Taxes, Heat, Water, Electric, Hot Water, Air Conditioner, Cable TV (incl. HBO/Showtime), High-speed Internet",
          "s5_parking": "None",
          "s5_storage": "Storage",
          "s5_hvac": "Central A/C; Hot water heat",
          "s5_laundry": "Common — each floor",
          "s5_flood": "Zone X (No)",
          "s5_misc": "Co-op — board approval required.",
          "s6_age": "1966 (co-op conversion 1983)",
          "s6_units": "315",
          "s6_amenities": "Community Room, Doorman/Concierge, Elevator, Fitness Center, Infinity Pool, Security (24hr), Shared Backyard",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Jennifer"
        }
      ]
    },
    {
      "deployedAt": "2026-07-10T03:59:44.181364+00:00",
      "meta": {
        "dateLabel": "Thu, July 9",
        "agent": "Christian Daugherty"
      },
      "client": {
        "name": "Tyler Krampf",
        "fub_url": "https://jillkbiggs.followupboss.com/2/people/view/170693",
        "meta": "3 properties · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Active buyer",
        "fields": [
          [
            "Budget",
            "~$699,000 (per FUB profile)"
          ],
          [
            "Location",
            "Hoboken / Hudson County"
          ],
          [
            "Home type",
            "Condo · 1-2 BR"
          ]
        ],
        "snapshotLines": [
          "~$699,000 (per FUB profile). Showing today (3 properties)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "125 Willow Ave, Unit 5S",
          "addr2": "Hoboken, NJ 07030",
          "type": "Condo",
          "ptype": "condo",
          "beds": "1 BR · 1 BA",
          "time": "5:00 PM",
          "price": "$665,000",
          "agent": "Nancy Holland",
          "phone": "(201) 306-2223",
          "zillow": "https://www.zillow.com/homedetails/125-Willow-Ave-APT-5S-Hoboken-NJ-07030/52962150_zpid/",
          "nav_addr": "",
          "disclosure": "",
          "flags": [],
          "s1_time": "5:00-5:15 PM",
          "s2_confirmed": "Yes - Confirmed (Auto Confirm)",
          "s2_source": "ShowingTime",
          "s3_occupancy": "Vacant (go-and-show)",
          "s3_lb": "Supra Box · On the roof",
          "s3_notes": "Lock the storm door and deadbolt on the roof door when leaving. Turn off all lights before leaving.",
          "snap": [
            [
              "$665K",
              "Asking"
            ],
            [
              "64d",
              "Days on mkt"
            ],
            [
              "$543",
              "HOA/mo"
            ],
            [
              "$6,397",
              "Taxes"
            ],
            [
              "760 sf",
              "Sq ft"
            ],
            [
              "$875",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 5/6: $725,000 -> Price cut 5/28: $699,000 (-$26K) -> Price cut 6/18: $665,000 (-$34K)",
          "s5_ownership": "Bought 2002 (seller: The Alix Biel Revocable Trust, Alix Biel Trustee - per seller's disclosure; predates Zillow's tracked price history, no Sold event shown there). Owned ~24 yrs - first time offered for sale in 25 years per listing. No rental history on Zillow.",
          "s5_hoainc": "Water",
          "s5_parking": "None",
          "s5_storage": "Basement storage (shared/open) for owners, per listing",
          "s5_hvac": "A/C Wall, Baseboard, Electric",
          "s5_laundry": "In-unit washer/dryer",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "",
          "s6_age": "Built 1920 (per public records - StreetEasy/Zillow/Realtor.com; seller's disclosure listed age as unknown)",
          "s6_units": "Approx. 9-10 units (unit numbering spans 1N/1S-4N/4S plus 5S; exact count not confirmed in public records)",
          "s6_amenities": "Private rooftop (shared)",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Tyler Krampf"
        },
        {
          "seq": "2",
          "addr1": "300 1st St, Unit 4S",
          "addr2": "Hoboken, NJ 07030",
          "type": "Condo",
          "ptype": "condo",
          "beds": "2 BR · 1 BA",
          "time": "5:30 PM",
          "price": "$649,000",
          "agent": "Timothy Fiorillo",
          "phone": "(610) 716-8122",
          "zillow": "https://www.zillow.com/homedetails/300-1st-St-APT-4S-Hoboken-NJ-07030/38882955_zpid/",
          "nav_addr": "",
          "disclosure": "",
          "flags": [
            {
              "t": "Double booked with 258 9th St #2 (5:30-6:00 PM)",
              "red": false
            }
          ],
          "s1_time": "5:30-6:00 PM - Double booked with 258 9th St #2",
          "s2_confirmed": "Yes - Confirmed",
          "s2_source": "ShowingTime",
          "s3_occupancy": "Tenant-occupied (until 7/31/2026).",
          "s3_lb": "Supra Box · On the gate, beneath the sign",
          "s3_notes": "Tenant may be present. Coordinate access timing with listing agent if needed. Wear shoe covers; turn off lights and lock the door before leaving.",
          "snap": [
            [
              "$649K",
              "Asking"
            ],
            [
              "2d",
              "Days on mkt"
            ],
            [
              "$565",
              "HOA/mo"
            ],
            [
              "$6,718",
              "Taxes"
            ],
            [
              "768 sf",
              "Sq ft"
            ],
            [
              "$845",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/7: $649,000 - no price changes since listing",
          "s5_ownership": "Bought 5/23/2007 @ $430,000 (per Zillow; seller's disclosure says Jan 2004 - dates differ slightly, likely contract vs. closing). Owned ~19 yrs. Rented ~2020 at $2,700-2,800/mo (removed 7/21/20); currently tenant-occupied through 7/31/2026.",
          "s5_hoainc": "Water",
          "s5_parking": "None",
          "s5_storage": "No mention",
          "s5_hvac": "A/C Central, Hot Air",
          "s5_laundry": "Common - Wash/Dry Room (shared building laundry)",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "",
          "s6_age": "Built 1901 (per public records)",
          "s6_units": "10 units (5 floors x N/S units; built 1901)",
          "s6_amenities": "Shared laundry room",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Tyler Krampf"
        },
        {
          "seq": "3",
          "addr1": "258 9th St, Unit 2",
          "addr2": "Hoboken, NJ 07030",
          "type": "Condo",
          "ptype": "condo",
          "beds": "1 BR · 1 BA",
          "time": "5:30 PM",
          "price": "$495,000",
          "agent": "Christine Ayubi",
          "phone": "(201) 669-0542",
          "zillow": "https://www.zillow.com/homedetails/258-9th-St-APT-2-Hoboken-NJ-07030/38884631_zpid/",
          "nav_addr": "",
          "disclosure": "",
          "flags": [
            {
              "t": "Double booked with 300 1st St #4S (5:30-6:00 PM)",
              "red": false
            }
          ],
          "s1_time": "5:30-6:00 PM - Double booked with 300 1st St #4S",
          "s2_confirmed": "Yes - Confirmed (Auto Confirm)",
          "s2_source": "ShowingTime",
          "s3_occupancy": "Vacant",
          "s3_lb": "Combination · Code: Combination code: 1004",
          "s3_notes": "",
          "snap": [
            [
              "$495K",
              "Asking"
            ],
            [
              "2d",
              "Days on mkt"
            ],
            [
              "$150",
              "HOA/mo"
            ],
            [
              "$4,763",
              "Taxes"
            ],
            [
              "528 sf",
              "Sq ft"
            ],
            [
              "$938",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/7: $495,000 - no price changes since listing",
          "s5_ownership": "Bought Jan 2004 (seller: Sohail Shahpar, per seller's disclosure; Zillow shows a Sold event 2/23/2005 at $255,000 - dates differ slightly). Owned ~22 yrs. Rented at $2,200/mo, most recently 2018-2019; currently vacant (tenant vacated as of listing).",
          "s5_hoainc": "Water",
          "s5_parking": "None",
          "s5_storage": "No mention",
          "s5_hvac": "A/C Window, Baseboard, Gas",
          "s5_laundry": "In-unit washer/dryer",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "Unit's share of flood insurance is approximately $2,000/yr (self-managed building), per broker remarks.",
          "s6_age": "Built 1900 (per public records)",
          "s6_units": "4 units (per public records - units 1-4)",
          "s6_amenities": "None",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Tyler Krampf"
        }
      ]
    },
    {
      "deployedAt": "2026-07-06T20:48:46.124026+00:00",
      "meta": {
        "dateLabel": "Mon, July 6",
        "agent": "Christian Daugherty"
      },
      "client": {
        "name": "",
        "fub_url": "",
        "meta": "3 properties",
        "stage": "Active buyer",
        "fields": [],
        "snapshotLines": [
          "Showing today (3 properties)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "118 The Promenade",
          "addr2": "Edgewater, NJ 07020",
          "type": "Condo",
          "ptype": "condo",
          "beds": "2 BR · 2 BA",
          "time": "",
          "price": "$618,000",
          "agent": "",
          "phone": "",
          "zillow": "https://www.zillow.com/homedetails/118-The-Promenade-Edgewater-NJ-07020/55450880_zpid/",
          "nav_addr": "195 River Rd",
          "disclosure": "",
          "flags": [
            {
              "t": "New $540.93/mo special assessment (since 2/1/26) + $97.63/mo roof-loan charge on top of $950 HOA — confirm remaining payoff term.",
              "red": false
            },
            {
              "t": "Listing agent name/phone not on provided MLS sheet (page 1 of 2) — verify before showing.",
              "red": false
            }
          ],
          "s1_time": "",
          "s2_confirmed": "",
          "s2_source": "",
          "s3_occupancy": "",
          "s3_lb": "",
          "s3_notes": "",
          "snap": [
            [
              "$618K",
              "Asking"
            ],
            [
              "98d",
              "Days on mkt"
            ],
            [
              "$950",
              "HOA/mo"
            ],
            [
              "$9,202",
              "Taxes"
            ]
          ],
          "s5_history": "Listed 3/30/26: $618,000 — no price changes since listing.",
          "s5_ownership": "",
          "s5_hoainc": "",
          "s5_parking": "1 indoor covered parking space",
          "s5_storage": "None",
          "s5_hvac": "Central A/C; gas hot air heat",
          "s5_laundry": "In-unit washer/dryer",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "Board requires 3x monthly maintenance as an additional charge at closing.",
          "s6_age": "Built 2002–2003 (per public building records; MLS lists 2000's)",
          "s6_units": "Not found after web search — large multi-building gated waterfront complex (unit numbers span 100s-340s+); exact total not published online.",
          "s6_amenities": "24hr doorman/security, exercise room, hot tub, sauna, community room, play area.",
          "s6_projects": "Roof replacement financed via a 15-year loan (started 6/1/17, ~6 yrs remaining).",
          "s6_assess": "New 5-year special assessment started 2/1/26: $540.93/month (on top of $950 HOA). Separate ongoing roof-loan assessment: $97.63/month (15-yr loan from 6/1/17).",
          "s6_financing": "",
          "s6_key": "(observed 2026-06-11) Go to guard shack for the keys then park next to the abandoned movie theater parking lot and enter through the green gate.",
          "similar": [],
          "commute": [],
          "client_name": ""
        },
        {
          "seq": "2",
          "addr1": "129 The Promenade",
          "addr2": "Edgewater, NJ 07020",
          "type": "Condo",
          "ptype": "condo",
          "beds": "2 BR · 2 BA",
          "time": "",
          "price": "$629,000",
          "agent": "Stephen Braconi",
          "phone": "(551) 804-8364",
          "zillow": "https://www.zillow.com/homedetails/129-The-Promenade-Edgewater-NJ-07020/462103908_zpid/",
          "nav_addr": "195 River Rd",
          "disclosure": "",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "",
          "s2_source": "",
          "s3_occupancy": "",
          "s3_lb": "",
          "s3_notes": "",
          "snap": [
            [
              "$629K",
              "Asking"
            ],
            [
              "66d",
              "Days on mkt"
            ],
            [
              "$1,100",
              "HOA/mo"
            ],
            [
              "$9,172",
              "Taxes"
            ]
          ],
          "s5_history": "Listed 10/8/25: $649,000 → Price cut 12/10/25: $629,000 (−$20K). Actual DOM: ~271 days (on market since 10/8/25 — relisted under new MLS#s 12/27/25→1/16/26→5/1/26, same price throughout)",
          "s5_ownership": "",
          "s5_hoainc": "",
          "s5_parking": "2 garage parking spots (deeded)",
          "s5_storage": "None",
          "s5_hvac": "Central A/C; forced hot air heat (gas)",
          "s5_laundry": "In-unit washer/dryer",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "",
          "s6_age": "Built 2002–2003 (per public building records; MLS lists 2002)",
          "s6_units": "Not found after web search — large multi-building gated waterfront complex (unit numbers span 100s-340s+); exact total not published online.",
          "s6_amenities": "Elevator.",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "(observed 2026-06-11) Go to guard shack for the keys then park next to the abandoned movie theater parking lot and enter through the green gate.",
          "similar": [],
          "commute": [],
          "client_name": ""
        },
        {
          "seq": "3",
          "addr1": "337 The Promenade, Unit 337",
          "addr2": "Edgewater, NJ 07020",
          "type": "Condo",
          "ptype": "condo",
          "beds": "2 BR · 2 BA",
          "time": "",
          "price": "$629,000",
          "agent": "",
          "phone": "",
          "zillow": "https://www.zillow.com/homedetails/337-The-Promenade-337-Edgewater-NJ-07020/461185374_zpid/",
          "nav_addr": "195 River Rd",
          "disclosure": "",
          "flags": [
            {
              "t": "Listing agent name/phone not on provided MLS sheet (page 1 of 2) — verify before showing.",
              "red": false
            },
            {
              "t": "MLS sheet lists zip 07013 — public records (Zillow/Redfin) show 07020 for this address; likely an MLS data-entry error.",
              "red": false
            }
          ],
          "s1_time": "",
          "s2_confirmed": "",
          "s2_source": "",
          "s3_occupancy": "",
          "s3_lb": "",
          "s3_notes": "",
          "snap": [
            [
              "$629K",
              "Asking"
            ],
            [
              "38d",
              "Days on mkt"
            ],
            [
              "$1,100",
              "HOA/mo"
            ],
            [
              "$9,820",
              "Taxes"
            ],
            [
              "1,506 sf",
              "Sq ft"
            ],
            [
              "$418",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 3/20/26: $629,000 — no price changes since listing. Actual DOM: ~108 days (on market since 3/20/26; MLS DOM resets to 38 after a 5/29/26 re-listing)",
          "s5_ownership": "",
          "s5_hoainc": "Maintenance-Common Area",
          "s5_parking": "1 indoor covered parking space",
          "s5_storage": "None",
          "s5_hvac": "Central A/C; gas hot air heat",
          "s5_laundry": "In-unit washer/dryer",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "",
          "s6_age": "Built 2002–2003 (per public building records; MLS lists 2000's)",
          "s6_units": "Not found after web search — large multi-building gated waterfront complex (unit numbers span 100s-340s+); exact total not published online.",
          "s6_amenities": "24hr doorman/security, exercise room, community room, fulltime handyman, gated community.",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "(observed 2026-06-11) Go to guard shack for the keys then park next to the abandoned movie theater parking lot and enter through the green gate.",
          "similar": [],
          "commute": [],
          "client_name": ""
        }
      ]
    },
    {
      "deployedAt": "2026-07-09T17:19:29.618536+00:00",
      "meta": {
        "dateLabel": "Wed, July 8",
        "agent": "Christian Daugherty"
      },
      "client": {
        "name": "",
        "fub_url": "",
        "meta": "3 properties",
        "stage": "Active buyer",
        "fields": [],
        "snapshotLines": [
          "Showing today (3 properties)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "121 41st St #4",
          "addr2": "Union City, NJ 07087",
          "type": "Condo",
          "ptype": "condo",
          "beds": "2 BR · 1 BA",
          "time": "",
          "price": "$299,000",
          "agent": "Sandy Melad",
          "phone": "(201) 205-8972",
          "zillow": "",
          "nav_addr": "",
          "disclosure": "",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "N/A: text-scheduled",
          "s2_source": "MLS remarks: text business card to LA Sandy Melad (201-205-8972) for showing instructions.",
          "s3_occupancy": "Not stated in MLS remarks (listing marked 'Easy to show') — clarify with listing agent.",
          "s3_lb": "",
          "s3_notes": "Text business card to Sandy Melad (201-205-8972) for showing instructions.",
          "snap": [
            [
              "$299K",
              "Asking"
            ],
            [
              "33d",
              "Days on mkt"
            ],
            [
              "$269",
              "HOA/mo"
            ],
            [
              "$4,411 (2025)",
              "Taxes"
            ],
            [
              "629 sf",
              "Sq ft"
            ],
            [
              "$475",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 6/5/26 at $299,000 (MLS-shown DOM only — actual history not verified this run; Zillow not pulled).",
          "s5_ownership": "Not pulled this run — Zillow/seller's disclosure skipped per instruction.",
          "s5_hoainc": "Heat, Water, Hot Water, Other (see remarks)",
          "s5_parking": "None",
          "s5_storage": "Private storage unit",
          "s5_hvac": "Window A/C; gas baseboard heat",
          "s5_laundry": "Common — basement (coin-operated); W&D hookup possible in-unit per remarks",
          "s5_flood": "Not pulled this run — flood zone lookup skipped per instruction.",
          "s5_misc": "",
          "s6_age": "Not pulled this run — building-data search skipped per instruction.",
          "s6_units": "Not pulled this run — building-data search skipped per instruction.",
          "s6_amenities": "Storage, Wash/Dry Room. In-unit: hardwood floors.",
          "s6_projects": "No mention",
          "s6_assess": "No mention",
          "s6_financing": "No mention",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": ""
        },
        {
          "seq": "2",
          "addr1": "3315 Pleasant Ave #407",
          "addr2": "Union City, NJ 07087",
          "type": "Condo",
          "ptype": "condo",
          "beds": "2 BR · 1 BA",
          "time": "",
          "price": "$324,000",
          "agent": "David Chittum",
          "phone": "(201) 388-9670",
          "zillow": "",
          "nav_addr": "",
          "disclosure": "",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "N/A: text-scheduled",
          "s2_source": "MLS remarks: 'Go and Show! Please contact Showingtime 855-957-1493.'",
          "s3_occupancy": "Vacant (go-and-show)",
          "s3_lb": "",
          "s3_notes": "Contact ShowingTime 855-957-1493. Questions to listing agent David Chittum, 201-388-9670.",
          "snap": [
            [
              "$324K",
              "Asking"
            ],
            [
              "104d",
              "Days on mkt"
            ],
            [
              "$465",
              "HOA/mo"
            ],
            [
              "$5,810 (2025)",
              "Taxes"
            ],
            [
              "710 sf",
              "Sq ft"
            ],
            [
              "$456",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 3/26/26 at $324,000 (MLS-shown DOM only — actual history not verified this run; Zillow not pulled).",
          "s5_ownership": "Not pulled this run — Zillow/seller's disclosure skipped per instruction.",
          "s5_hoainc": "Heat, Water, Hot Water",
          "s5_parking": "None",
          "s5_storage": "No mention",
          "s5_hvac": "Window A/C; gas radiator/steam heat",
          "s5_laundry": "Common — laundry room (Harbor View bldg; exact location not specified)",
          "s5_flood": "Not pulled this run — flood zone lookup skipped per instruction.",
          "s5_misc": "",
          "s6_age": "Not pulled this run — building-data search skipped per instruction.",
          "s6_units": "Not pulled this run — building-data search skipped per instruction.",
          "s6_amenities": "Elevator, Wash/Dry Room, Intercom. In-unit: hardwood floors. (Harbor View Condominium)",
          "s6_projects": "No mention",
          "s6_assess": "No mention",
          "s6_financing": "No mention",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": ""
        },
        {
          "seq": "3",
          "addr1": "500 Central Ave #314",
          "addr2": "Union City, NJ 07087",
          "type": "Condo",
          "ptype": "condo",
          "beds": "1 BR · 1 BA",
          "time": "",
          "price": "$299,987",
          "agent": "Jeffrey Radlin",
          "phone": "(201) 705-9999",
          "zillow": "",
          "nav_addr": "",
          "disclosure": "",
          "flags": [
            {
              "t": "Parking recorded as 'None' — MLS shows '1 Car, Other-See Remarks'; broker remarks describe a paid 3rd-party on-site lot at $250/mo (not an included/deeded spot).",
              "red": false
            }
          ],
          "s1_time": "",
          "s2_confirmed": "N/A: text-scheduled",
          "s2_source": "MLS remarks: 'Call Showing time to schedule. Go and Show, vacant.'",
          "s3_occupancy": "Vacant (per MLS remarks)",
          "s3_lb": "",
          "s3_notes": "Keys with doorman. Unit is to the right (South) elevators when looking at front desk — get fob from doorman, go down opposite hallway past the North elevator. Mgmt: Associa Community, 201-330-1131.",
          "snap": [
            [
              "$300K",
              "Asking"
            ],
            [
              "35d",
              "Days on mkt"
            ],
            [
              "$644",
              "HOA/mo"
            ],
            [
              "$5,796 (2025)",
              "Taxes"
            ],
            [
              "821 sf",
              "Sq ft"
            ],
            [
              "$365",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 6/3/26 at $299,987, price-reduced for 4th of July special (MLS-shown DOM only — actual history not verified this run; Zillow not pulled).",
          "s5_ownership": "Not pulled this run — Zillow/seller's disclosure skipped per instruction.",
          "s5_hoainc": "Heat, Gas, Hot Water",
          "s5_parking": "None",
          "s5_storage": "No mention",
          "s5_hvac": "Wall A/C; hot water heat, heat pump",
          "s5_laundry": "Common — main level, North side (per remarks)",
          "s5_flood": "Not pulled this run — flood zone lookup skipped per instruction.",
          "s5_misc": "",
          "s6_age": "Not pulled this run — building-data search skipped per instruction.",
          "s6_units": "Not pulled this run — building-data search skipped per instruction.",
          "s6_amenities": "Community Room, Doorman, Elevator, Exercise Room, Play Area, Shops on Premises, Wash/Dry Room, Shared Backyard. In-unit: hardwood floors. (The Lenox)",
          "s6_projects": "No mention",
          "s6_assess": "No mention",
          "s6_financing": "No mention",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": ""
        }
      ]
    }
  ]
};
