/* ============================================================
   FIELD COMPANION — SHOWING DATA   (auto-generated)
   ------------------------------------------------------------
   Generated by build_field_companion.py from the same prepped
   showing dicts that build the packet. This is the ONLY file
   the showing-prep workflow overwrites; the app shell
   (field_companion.html) is never touched per showing.

   DO NOT hand-edit — rerun the generator instead.
   ============================================================ */
window.FC_DATA = {
  "meta": {
    "dateLabel": "Fri, July 31",
    "agent": "Christian Daugherty",
    "deployedAt": "2026-07-31T21:00:39.000977+00:00"
  },
  "appointments": [
    {
      "date": "Fri, July 31",
      "client": {
        "name": "",
        "fub_url": "",
        "meta": "3 properties · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Active buyer",
        "fields": [],
        "snapshotLines": [
          "Showing today (3 properties)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "380 Luis M Marin Blvd #2R",
          "addr2": "Jersey City, NJ 07302",
          "type": "Condominium (Row House, Multi-Level)",
          "ptype": "multi",
          "beds": "2 BR / 2 full + 1 half bath",
          "time": "5:00 PM",
          "price": "$849,000",
          "agent": "Pavel Saikin",
          "phone": "(908) 868-9552",
          "zillow": "https://www.zillow.com/homedetails/380-Luis-M-Marin-Blvd-2R-Jersey-City-NJ-07302/2081554800_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/3/HUDSON_358099.pdf",
          "flags": [],
          "s1_time": "5:00 PM",
          "s2_confirmed": "Yes - Confirmed (1st Showing (Auto Confirm))",
          "s2_source": "ShowingTime confirmation (screenshot provided by Christian)",
          "s3_occupancy": "No mention",
          "s3_lb": "Keypad · Code: Unit door: 2692 · No mention",
          "s3_notes": "Alarm details: none provided. Access listed as Keypad; unit door code supplied by Christian.",
          "snap": [
            [
              "$849K",
              "Asking"
            ],
            [
              "38d",
              "Days on mkt"
            ],
            [
              "$542/mo",
              "HOA/mo"
            ],
            [
              "$14,267/yr (2025)",
              "Taxes"
            ],
            [
              "1,150 sq ft",
              "Sq ft"
            ],
            [
              "$738/sq",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 5/1: $869K -> Price cut 6/8: $849K (-$20K). Actual DOM: 91 days (continuously on market since 5/1/2026; MLS DOM resets because the cycle spans 3 MLS#s: 260008145 -> 260009931 -> 260012233).",
          "s5_ownership": "Bought 2/27/20 @ $695K. Owned ~6.4 yrs. No rental history on Zillow. (Prior sales: 5/18/15 @ $612K, 12/3/10 @ $405K.)",
          "s5_hoainc": "Water",
          "s5_parking": "1 Car, Other-See Remarks — no deeded/garage spot detailed in MLS; broker remarks note rental parking options 1 min away at 160 Morgan St",
          "s5_storage": "No mention",
          "s5_hvac": "Central A/C; hot air, gas heat",
          "s5_laundry": "In-unit — washer/dryer listed in appliances",
          "s5_flood": "Zone AE (Yes) - Special Flood Hazard Area. Source: NJDEP mirror of the FEMA NFHL (FEMA's own service is currently erroring). First Street Flood Factor 8/10.",
          "s5_misc": "MLS status per ShowingTime: ACTIVE (Hudson County MLS #260012233).",
          "s6_age": "1900 (Zillow + Trulia). Historic loft building in the Powerhouse Arts District — industrial-to-residential conversion; conversion year not found.",
          "s6_units": "Not found — no published unit count. Past listings show only 2R / 3R / 4R (4R is the top-floor penthouse duplex), i.e. a small walk-up-scale loft building.",
          "s6_amenities": "No shared amenities surfaced — no doorman, gym, roof deck or common laundry in any source. Intercom is the only building feature listed. Elevator: never mentioned — assume walk-up until confirmed. In-unit W/D + central A/C per past listings. HOA on this line has run $456-$542/mo (incl. water).",
          "s6_projects": "Not found.",
          "s6_assess": "Not found.",
          "s6_financing": "Not found. Worth asking: a small (<10 unit) 1900 loft conversion is the profile where FHA approval / warrantability and rental caps bite.",
          "s6_key": "No entry in property_database.md - first visit. Public data on this building is unusually thin (StreetEasy has no building profile). Parking is contradictory across sources (Zillow #2R '1 Car'; Compass #2R and Trulia 'None') - treat as NOT included until the listing agent confirms. Ask on site: unit count + elevator; is any parking deeded or rented and where; any assessment pending; FHA / rental-cap status.",
          "similar": [],
          "commute": [],
          "client_name": ""
        },
        {
          "seq": "2",
          "addr1": "230 3rd St #1",
          "addr2": "Jersey City, NJ 07302",
          "type": "Condominium (Row House — garden/parlor duplex)",
          "ptype": "condo",
          "beds": "2 BR / 1 full bath",
          "time": "5:30 PM",
          "price": "$650,000",
          "agent": "Brian Henry",
          "phone": "(201) 401-1457",
          "zillow": "https://www.zillow.com/homedetails/230-3rd-St-1-Jersey-City-NJ-07302/248883329_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/5/HUDSON_362720.pdf",
          "flags": [],
          "s1_time": "5:30 PM",
          "s2_confirmed": "Yes - Confirmed (1st Showing)",
          "s2_source": "ShowingTime confirmation (screenshot provided by Christian)",
          "s3_occupancy": "No mention",
          "s3_lb": "Supra · Code: No mention · No mention",
          "s3_notes": "ShowingTime: access details not provided — showing instructions say call Brian at 201-401-1457 for listing + showing info. Supra per Christian. NOTE: MLS status shows WITHDRAWN - CONDITIONAL.",
          "snap": [
            [
              "$650K",
              "Asking"
            ],
            [
              "34d",
              "Days on mkt"
            ],
            [
              "$500/mo",
              "HOA/mo"
            ],
            [
              "$13,529/yr (2025)",
              "Taxes"
            ],
            [
              "1,100 sq ft",
              "Sq ft"
            ],
            [
              "$591/sq",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 6/26: $795K → Price cut 7/7: $650K (-$145K) → Listing removed 7/30 (withdrawn — 34 days on market)",
          "s5_ownership": "Bought 5/1/83 @ $43K — whole building; #1 is a newly created condo unit with no separate sale on record. Owned ~43 yrs. No rental history on Zillow. Prior: Sold 11/1/80 @ $22K.",
          "s5_hoainc": "Heat, water, hot water",
          "s5_parking": "None — MLS Parking Available = None",
          "s5_storage": "No mention",
          "s5_hvac": "Baseboard gas heat; no central A/C listed",
          "s5_laundry": "No mention — appliances listed are refrigerator and gas oven/range only",
          "s5_flood": "Zone X shaded — 0.2% annual chance (No)",
          "s5_misc": "Seller will consider ALL-CASH offers only; all offers require proof of funds through the listing broker. Sold 'as is' — renovation project. Exclusions: light fixtures (2 chandeliers on parlor floor, 4 sconces on garden level).",
          "s6_age": "1885 (Hudson County tax record, Block 11105 Lot 22). 3-story brick-and-stucco rowhouse. Conversion/gut-reno year not found; facade recently restored and front windows newly replaced.",
          "s6_units": "2 (tax record: duplex, 2 living units). Association on record: '230 Third Street Condominium'. Unit 1 is the lower duplex with the private garden.",
          "s6_amenities": "No shared amenities (StreetEasy: 'No info on amenities'). Unit-level: private garden, eat-in kitchen, soaring ceilings, marble mantels, hardwood, original moldings. Parking: none on site. Heat: gas baseboard. Central A/C: not found. Laundry: not found.",
          "s6_projects": "Facade restored + front windows replaced (completed). HOA $500/mo.",
          "s6_assess": "Not found.",
          "s6_financing": "Not found. Relevant facts: sold strictly as-is, 'awaiting a complete renovation', and it is a 2-unit association - both can limit conventional/FHA options.",
          "s6_key": "No entry in property_database.md - first visit. A 2-unit association is the headline: budget, reserves and financing all hinge on one other owner.",
          "similar": [],
          "commute": [],
          "client_name": ""
        },
        {
          "seq": "3",
          "addr1": "226 1st St #401 (4A)",
          "addr2": "Jersey City, NJ 07302",
          "type": "Condominium (Brownstone), 4th floor",
          "ptype": "condo",
          "beds": "MLS room count: 2 BR / 1 full + 1 half bath. Advertising remarks describe it as a 1-bath home with a den — verify bed/bath count on site.",
          "time": "5:30 PM",
          "price": "$689,000",
          "agent": "Michelle Mumoli",
          "phone": "(973) 454-3543",
          "zillow": "https://www.zillow.com/homedetails/226-1st-St-401-4A-Jersey-City-NJ-07302/464208671_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/8/HUDSON_361995.pdf",
          "flags": [],
          "s1_time": "5:30 PM",
          "s2_confirmed": "Yes - Confirmed (1st Showing)",
          "s2_source": "ShowingTime confirmation (screenshot provided by Christian)",
          "s3_occupancy": "No mention",
          "s3_lb": "Combination lockbox + gate code · Code: Combo 1978 (gate/LB); unit top-lock keypad 2829 · Left side railing",
          "s3_notes": "Combo code 1978 on left side railing. PLEASE REMOVE SHOES. Silver key in LB opens unit bottom lock; keypad code 2829 for unit top lock. On exit: turn off lights, lock doors, keys back in LB, scramble code. Alarm details: none provided.",
          "snap": [
            [
              "$689K",
              "Asking"
            ],
            [
              "2d",
              "Days on mkt"
            ],
            [
              "$315/mo",
              "HOA/mo"
            ],
            [
              "$12,238/yr (2025) — listing says taxes to be independently verified with the City of Jersey City",
              "Taxes"
            ],
            [
              "940 sq ft",
              "Sq ft"
            ],
            [
              "$733/sq",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/29: $689K",
          "s5_ownership": "Bought 8/18/20 @ $615K. Owned ~5.9 yrs. No rental history on Zillow. Prior: Sold 10/11/02 @ $195K; Sold 1/3/00 @ $121.5K.",
          "s5_hoainc": "Heat, hot water, gas, water/sewer and general building maintenance (self-managed condo)",
          "s5_parking": "None — MLS Parking Available = None",
          "s5_storage": "No mention",
          "s5_hvac": "Window A/C units; baseboard gas heat — no central air",
          "s5_laundry": "Washer/dryer listed in unit appliances; building also has a common wash/dry room",
          "s5_flood": "Zone X (No)",
          "s5_misc": "Offers by email in NJAR contract form with pre-approval or proof of funds to michelle.mumoli@compass.com, cc Marielle at mumolicollective@gmail.com. Listing names Megan McDermott, Cross Country Mortgage, 973-534-340x as a preapproval contact (informational only).",
          "s6_age": "Not confirmed. Zillow shows 1980 on a sister unit (likely a placeholder); StreetEasy and the brokerage record for #2A show no year built; tax record unreachable. NOTE: the loft-conversion assumption is NOT supported - the Coldwell Banker record for #2A calls it a brick 'Brownstone'. Verify age on the MLS sheet.",
          "s6_units": "Not found officially. Unit designations in listing history (#1, #1B, #2A, #2B, #3A, #4A, #4B, #101, #BA) imply roughly 8-9 units over ~4 floors plus a basement unit - inferred, not verified.",
          "s6_amenities": "Common laundry room in the basement (MLS 'Wash/Dry Room' for #2A; HOA permits in-unit W/D). Shared roof deck ('Public Roof Top'). Intercom. Gated entry. Parking: none. No elevator mentioned anywhere - assume a 4-story walk-up, which matters for a top-floor unit. Building HOA runs ~$225-$236/mo on other units; the fee for #401 was not found.",
          "s6_projects": "Not found.",
          "s6_assess": "Not found.",
          "s6_financing": "Not found. Small (~8-9 unit) association - worth asking the listing agent about warrantability and rental caps.",
          "s6_key": "No entry in property_database.md - first visit. Ask on site: true year built + any gut-reno; elevator or walk-up; unit count, the actual HOA for #401, and any assessment or financing restriction.",
          "similar": [],
          "commute": [],
          "client_name": ""
        }
      ]
    }
  ],
  "client": {
    "name": "",
    "fub_url": "",
    "meta": "3 properties · Buyer · Christian Daugherty, Jill Biggs Group",
    "stage": "Active buyer",
    "fields": [],
    "snapshotLines": [
      "Showing today (3 properties)."
    ]
  },
  "props": [
    {
      "seq": "1",
      "addr1": "380 Luis M Marin Blvd #2R",
      "addr2": "Jersey City, NJ 07302",
      "type": "Condominium (Row House, Multi-Level)",
      "ptype": "multi",
      "beds": "2 BR / 2 full + 1 half bath",
      "time": "5:00 PM",
      "price": "$849,000",
      "agent": "Pavel Saikin",
      "phone": "(908) 868-9552",
      "zillow": "https://www.zillow.com/homedetails/380-Luis-M-Marin-Blvd-2R-Jersey-City-NJ-07302/2081554800_zpid/",
      "nav_addr": "",
      "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/3/HUDSON_358099.pdf",
      "flags": [],
      "s1_time": "5:00 PM",
      "s2_confirmed": "Yes - Confirmed (1st Showing (Auto Confirm))",
      "s2_source": "ShowingTime confirmation (screenshot provided by Christian)",
      "s3_occupancy": "No mention",
      "s3_lb": "Keypad · Code: Unit door: 2692 · No mention",
      "s3_notes": "Alarm details: none provided. Access listed as Keypad; unit door code supplied by Christian.",
      "snap": [
        [
          "$849K",
          "Asking"
        ],
        [
          "38d",
          "Days on mkt"
        ],
        [
          "$542/mo",
          "HOA/mo"
        ],
        [
          "$14,267/yr (2025)",
          "Taxes"
        ],
        [
          "1,150 sq ft",
          "Sq ft"
        ],
        [
          "$738/sq",
          "Per sq ft"
        ]
      ],
      "s5_history": "Listed 5/1: $869K -> Price cut 6/8: $849K (-$20K). Actual DOM: 91 days (continuously on market since 5/1/2026; MLS DOM resets because the cycle spans 3 MLS#s: 260008145 -> 260009931 -> 260012233).",
      "s5_ownership": "Bought 2/27/20 @ $695K. Owned ~6.4 yrs. No rental history on Zillow. (Prior sales: 5/18/15 @ $612K, 12/3/10 @ $405K.)",
      "s5_hoainc": "Water",
      "s5_parking": "1 Car, Other-See Remarks — no deeded/garage spot detailed in MLS; broker remarks note rental parking options 1 min away at 160 Morgan St",
      "s5_storage": "No mention",
      "s5_hvac": "Central A/C; hot air, gas heat",
      "s5_laundry": "In-unit — washer/dryer listed in appliances",
      "s5_flood": "Zone AE (Yes) - Special Flood Hazard Area. Source: NJDEP mirror of the FEMA NFHL (FEMA's own service is currently erroring). First Street Flood Factor 8/10.",
      "s5_misc": "MLS status per ShowingTime: ACTIVE (Hudson County MLS #260012233).",
      "s6_age": "1900 (Zillow + Trulia). Historic loft building in the Powerhouse Arts District — industrial-to-residential conversion; conversion year not found.",
      "s6_units": "Not found — no published unit count. Past listings show only 2R / 3R / 4R (4R is the top-floor penthouse duplex), i.e. a small walk-up-scale loft building.",
      "s6_amenities": "No shared amenities surfaced — no doorman, gym, roof deck or common laundry in any source. Intercom is the only building feature listed. Elevator: never mentioned — assume walk-up until confirmed. In-unit W/D + central A/C per past listings. HOA on this line has run $456-$542/mo (incl. water).",
      "s6_projects": "Not found.",
      "s6_assess": "Not found.",
      "s6_financing": "Not found. Worth asking: a small (<10 unit) 1900 loft conversion is the profile where FHA approval / warrantability and rental caps bite.",
      "s6_key": "No entry in property_database.md - first visit. Public data on this building is unusually thin (StreetEasy has no building profile). Parking is contradictory across sources (Zillow #2R '1 Car'; Compass #2R and Trulia 'None') - treat as NOT included until the listing agent confirms. Ask on site: unit count + elevator; is any parking deeded or rented and where; any assessment pending; FHA / rental-cap status.",
      "similar": [],
      "commute": [],
      "client_name": ""
    },
    {
      "seq": "2",
      "addr1": "230 3rd St #1",
      "addr2": "Jersey City, NJ 07302",
      "type": "Condominium (Row House — garden/parlor duplex)",
      "ptype": "condo",
      "beds": "2 BR / 1 full bath",
      "time": "5:30 PM",
      "price": "$650,000",
      "agent": "Brian Henry",
      "phone": "(201) 401-1457",
      "zillow": "https://www.zillow.com/homedetails/230-3rd-St-1-Jersey-City-NJ-07302/248883329_zpid/",
      "nav_addr": "",
      "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/5/HUDSON_362720.pdf",
      "flags": [],
      "s1_time": "5:30 PM",
      "s2_confirmed": "Yes - Confirmed (1st Showing)",
      "s2_source": "ShowingTime confirmation (screenshot provided by Christian)",
      "s3_occupancy": "No mention",
      "s3_lb": "Supra · Code: No mention · No mention",
      "s3_notes": "ShowingTime: access details not provided — showing instructions say call Brian at 201-401-1457 for listing + showing info. Supra per Christian. NOTE: MLS status shows WITHDRAWN - CONDITIONAL.",
      "snap": [
        [
          "$650K",
          "Asking"
        ],
        [
          "34d",
          "Days on mkt"
        ],
        [
          "$500/mo",
          "HOA/mo"
        ],
        [
          "$13,529/yr (2025)",
          "Taxes"
        ],
        [
          "1,100 sq ft",
          "Sq ft"
        ],
        [
          "$591/sq",
          "Per sq ft"
        ]
      ],
      "s5_history": "Listed 6/26: $795K → Price cut 7/7: $650K (-$145K) → Listing removed 7/30 (withdrawn — 34 days on market)",
      "s5_ownership": "Bought 5/1/83 @ $43K — whole building; #1 is a newly created condo unit with no separate sale on record. Owned ~43 yrs. No rental history on Zillow. Prior: Sold 11/1/80 @ $22K.",
      "s5_hoainc": "Heat, water, hot water",
      "s5_parking": "None — MLS Parking Available = None",
      "s5_storage": "No mention",
      "s5_hvac": "Baseboard gas heat; no central A/C listed",
      "s5_laundry": "No mention — appliances listed are refrigerator and gas oven/range only",
      "s5_flood": "Zone X shaded — 0.2% annual chance (No)",
      "s5_misc": "Seller will consider ALL-CASH offers only; all offers require proof of funds through the listing broker. Sold 'as is' — renovation project. Exclusions: light fixtures (2 chandeliers on parlor floor, 4 sconces on garden level).",
      "s6_age": "1885 (Hudson County tax record, Block 11105 Lot 22). 3-story brick-and-stucco rowhouse. Conversion/gut-reno year not found; facade recently restored and front windows newly replaced.",
      "s6_units": "2 (tax record: duplex, 2 living units). Association on record: '230 Third Street Condominium'. Unit 1 is the lower duplex with the private garden.",
      "s6_amenities": "No shared amenities (StreetEasy: 'No info on amenities'). Unit-level: private garden, eat-in kitchen, soaring ceilings, marble mantels, hardwood, original moldings. Parking: none on site. Heat: gas baseboard. Central A/C: not found. Laundry: not found.",
      "s6_projects": "Facade restored + front windows replaced (completed). HOA $500/mo.",
      "s6_assess": "Not found.",
      "s6_financing": "Not found. Relevant facts: sold strictly as-is, 'awaiting a complete renovation', and it is a 2-unit association - both can limit conventional/FHA options.",
      "s6_key": "No entry in property_database.md - first visit. A 2-unit association is the headline: budget, reserves and financing all hinge on one other owner.",
      "similar": [],
      "commute": [],
      "client_name": ""
    },
    {
      "seq": "3",
      "addr1": "226 1st St #401 (4A)",
      "addr2": "Jersey City, NJ 07302",
      "type": "Condominium (Brownstone), 4th floor",
      "ptype": "condo",
      "beds": "MLS room count: 2 BR / 1 full + 1 half bath. Advertising remarks describe it as a 1-bath home with a den — verify bed/bath count on site.",
      "time": "5:30 PM",
      "price": "$689,000",
      "agent": "Michelle Mumoli",
      "phone": "(973) 454-3543",
      "zillow": "https://www.zillow.com/homedetails/226-1st-St-401-4A-Jersey-City-NJ-07302/464208671_zpid/",
      "nav_addr": "",
      "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/8/HUDSON_361995.pdf",
      "flags": [],
      "s1_time": "5:30 PM",
      "s2_confirmed": "Yes - Confirmed (1st Showing)",
      "s2_source": "ShowingTime confirmation (screenshot provided by Christian)",
      "s3_occupancy": "No mention",
      "s3_lb": "Combination lockbox + gate code · Code: Combo 1978 (gate/LB); unit top-lock keypad 2829 · Left side railing",
      "s3_notes": "Combo code 1978 on left side railing. PLEASE REMOVE SHOES. Silver key in LB opens unit bottom lock; keypad code 2829 for unit top lock. On exit: turn off lights, lock doors, keys back in LB, scramble code. Alarm details: none provided.",
      "snap": [
        [
          "$689K",
          "Asking"
        ],
        [
          "2d",
          "Days on mkt"
        ],
        [
          "$315/mo",
          "HOA/mo"
        ],
        [
          "$12,238/yr (2025) — listing says taxes to be independently verified with the City of Jersey City",
          "Taxes"
        ],
        [
          "940 sq ft",
          "Sq ft"
        ],
        [
          "$733/sq",
          "Per sq ft"
        ]
      ],
      "s5_history": "Listed 7/29: $689K",
      "s5_ownership": "Bought 8/18/20 @ $615K. Owned ~5.9 yrs. No rental history on Zillow. Prior: Sold 10/11/02 @ $195K; Sold 1/3/00 @ $121.5K.",
      "s5_hoainc": "Heat, hot water, gas, water/sewer and general building maintenance (self-managed condo)",
      "s5_parking": "None — MLS Parking Available = None",
      "s5_storage": "No mention",
      "s5_hvac": "Window A/C units; baseboard gas heat — no central air",
      "s5_laundry": "Washer/dryer listed in unit appliances; building also has a common wash/dry room",
      "s5_flood": "Zone X (No)",
      "s5_misc": "Offers by email in NJAR contract form with pre-approval or proof of funds to michelle.mumoli@compass.com, cc Marielle at mumolicollective@gmail.com. Listing names Megan McDermott, Cross Country Mortgage, 973-534-340x as a preapproval contact (informational only).",
      "s6_age": "Not confirmed. Zillow shows 1980 on a sister unit (likely a placeholder); StreetEasy and the brokerage record for #2A show no year built; tax record unreachable. NOTE: the loft-conversion assumption is NOT supported - the Coldwell Banker record for #2A calls it a brick 'Brownstone'. Verify age on the MLS sheet.",
      "s6_units": "Not found officially. Unit designations in listing history (#1, #1B, #2A, #2B, #3A, #4A, #4B, #101, #BA) imply roughly 8-9 units over ~4 floors plus a basement unit - inferred, not verified.",
      "s6_amenities": "Common laundry room in the basement (MLS 'Wash/Dry Room' for #2A; HOA permits in-unit W/D). Shared roof deck ('Public Roof Top'). Intercom. Gated entry. Parking: none. No elevator mentioned anywhere - assume a 4-story walk-up, which matters for a top-floor unit. Building HOA runs ~$225-$236/mo on other units; the fee for #401 was not found.",
      "s6_projects": "Not found.",
      "s6_assess": "Not found.",
      "s6_financing": "Not found. Small (~8-9 unit) association - worth asking the listing agent about warrantability and rental caps.",
      "s6_key": "No entry in property_database.md - first visit. Ask on site: true year built + any gut-reno; elevator or walk-up; unit count, the actual HOA for #401, and any assessment or financing restriction.",
      "similar": [],
      "commute": [],
      "client_name": ""
    }
  ],
  "history": [
    {
      "deployedAt": "2026-07-28T04:57:05.959190+00:00",
      "meta": {
        "dateLabel": "Tue, July 28",
        "agent": "Christian Daugherty"
      },
      "client": {
        "name": "Jake Triarsi",
        "fub_url": "https://jillkbiggs.followupboss.com/2/people/view/189400",
        "meta": "5 properties · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Showing homes",
        "fields": [
          [
            "Budget",
            "$799,000"
          ],
          [
            "Location",
            "Hoboken, NJ"
          ],
          [
            "Home type",
            "Condo"
          ],
          [
            "Timeline",
            "Lease ended June 30th"
          ]
        ],
        "snapshotLines": [
          "$799,000. Showing today (5 properties)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "734 Adams St",
          "addr2": "#3A · Hoboken NJ 07030",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "2 BR / 1 BA",
          "time": "",
          "price": "$550,000",
          "agent": "Soha Fontaine ·  (cell) · Compass NJ",
          "phone": "917-892-8977",
          "zillow": "https://www.zillow.com/homedetails/734-Adams-St-APT-3A-Hoboken-NJ-07030/88857375_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/4/HUDSON_358733.pdf",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "Yes — Confirmed (Auto Confirm)",
          "s2_source": "ShowingTime — Auto Confirm, appointment #885546622, confirmed 6:00 PM – 6:30 PM, Tue 7/28",
          "s3_occupancy": "Vacant (go-and-show)",
          "s3_lb": "Supra",
          "s3_notes": "",
          "snap": [
            [
              "$550K",
              "Asking"
            ],
            [
              "8d",
              "Days on mkt"
            ],
            [
              "$400/mo",
              "HOA/mo"
            ],
            [
              "$5,215",
              "Taxes"
            ],
            [
              "537 sq ft",
              "Sq ft"
            ],
            [
              "$1,024/sq",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/20/26: $550K. No cuts.",
          "s5_ownership": "Bought 2/3/20 @ $375K. Rented @ $3,200/mo (listed/removed 2024 & 2025). Listed for sale 7/20/26. Owned ~6.5 yrs.",
          "s5_hoainc": "",
          "s5_parking": "None",
          "s5_storage": "Common storage in building",
          "s5_hvac": "Wall A/C; baseboard gas heat",
          "s5_laundry": "Common (wash/dry room in lower level)",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "3rd floor walk-up (no elevator per ad remarks)",
          "s6_age": "1910",
          "s6_units": "22",
          "s6_amenities": "Intercom; shared backyard",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Jake Triarsi"
        },
        {
          "seq": "2",
          "addr1": "73 Madison St",
          "addr2": "#1S · Hoboken NJ 07030",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "2 BR / 1 BA",
          "time": "",
          "price": "$725,000",
          "agent": "Thomas Kramer ·  (cell) · Weichert Realtors",
          "phone": "201-458-3476",
          "zillow": "https://www.zillow.com/homedetails/73-Madison-St-APT-1S-Hoboken-NJ-07030/38882435_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/5/HUDSON_359982.pdf",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "Awaiting confirmation",
          "s2_source": "ShowingTime — Auto Confirm listing (MLS 260013775, Active, 73 Madison St #1S); no appointment found for 7/28. Needs booking — will Auto Confirm instantly once scheduled.",
          "s3_occupancy": "Vacant",
          "s3_lb": "",
          "s3_notes": "",
          "snap": [
            [
              "$725K",
              "Asking"
            ],
            [
              "14d",
              "Days on mkt"
            ],
            [
              "$440/mo",
              "HOA/mo"
            ],
            [
              "$6,872",
              "Taxes"
            ],
            [
              "702 sq ft",
              "Sq ft"
            ],
            [
              "$1,033/sq",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/14/26: $725K. No cuts.",
          "s5_ownership": "Bought 5/15/23 @ $650K. No rental history on Zillow. Owned ~2.2 yrs.",
          "s5_hoainc": "Water",
          "s5_parking": "None (parking nearby for additional fee per broker remarks)",
          "s5_storage": "Private storage in building",
          "s5_hvac": "Wall A/C; baseboard heat",
          "s5_laundry": "Common W/D room in building",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "",
          "s6_age": "1883",
          "s6_units": "6",
          "s6_amenities": "Intercom; private backyard",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Jake Triarsi"
        },
        {
          "seq": "3",
          "addr1": "132 Jackson St",
          "addr2": "#1N · Hoboken NJ 07030",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "2 BR / 1 BA",
          "time": "",
          "price": "$715,000",
          "agent": "Anthony Packwood ·  (cell) · Engel & Volkers Hoboken",
          "phone": "929-309-5530",
          "zillow": "https://www.zillow.com/homedetails/132-Jackson-St-APT-1N-Hoboken-NJ-07030/38882700_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/9/HUDSON_358294.pdf",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "UNVERIFIED: listing CND, not in ShowingTime — confirm with LA",
          "s2_source": "ShowingTime returned 0 results for MLS 260012699 (CND per MLS ~7/22/26). Confirm with LA Anthony Packwood · 929-309-5530.",
          "s3_occupancy": "Unknown — CND listing not in ShowingTime",
          "s3_lb": "No mention · No mention",
          "s3_notes": "Property under contract (CND). Confirm whether backup showing is proceeding and how to access with LA: Anthony Packwood · 929-309-5530.",
          "snap": [
            [
              "$715K",
              "Asking"
            ],
            [
              "22d",
              "Days on mkt"
            ],
            [
              "$325/mo",
              "HOA/mo"
            ],
            [
              "$5,682",
              "Taxes"
            ],
            [
              "670 sq ft",
              "Sq ft"
            ],
            [
              "$1,067/sq",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 6/30/26: $715K. Listing removed 7/22/26 (off market — note for coordinator).",
          "s5_ownership": "Bought 4/5/21 @ $455K. No rental history on Redfin. Owned ~5.3 yrs.",
          "s5_hoainc": "Water",
          "s5_parking": "None",
          "s5_storage": "Private basement storage",
          "s5_hvac": "Central A/C; hot air (electric)",
          "s5_laundry": "In-unit W/D",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "STATUS: Conditional (under contract ~7/22/26). Unit has private terrace.",
          "s6_age": "1986",
          "s6_units": "6",
          "s6_amenities": "Terrace (unit-specific); private backyard",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Jake Triarsi"
        },
        {
          "seq": "4",
          "addr1": "84 Monroe St",
          "addr2": "#3 · Hoboken NJ 07030",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "2 BR / 1 BA",
          "time": "",
          "price": "$674,000",
          "agent": "Margaret M Crimmins ·  (cell) · Corcoran Sawyer Smith",
          "phone": "201-240-6531",
          "zillow": "https://www.zillow.com/homedetails/84-Monroe-St-APT-3-Hoboken-NJ-07030/38882355_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/0/HUDSON_355927.pdf",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "UNVERIFIED: listing CND, not in ShowingTime — confirm with LA",
          "s2_source": "ShowingTime returned 0 results for MLS 260011070 (CND per MLS ~7/27/26). Confirm with LA Margaret M Crimmins · 201-240-6531.",
          "s3_occupancy": "Unknown — CND listing not in ShowingTime",
          "s3_lb": "No mention · No mention",
          "s3_notes": "Property under contract (CND) as of today. Confirm whether backup showing is proceeding and how to access with LA: Margaret M Crimmins · 201-240-6531.",
          "snap": [
            [
              "$674K",
              "Asking"
            ],
            [
              "48d",
              "Days on mkt"
            ],
            [
              "$509/mo",
              "HOA/mo"
            ],
            [
              "$6,695 (2025)",
              "Taxes"
            ],
            [
              "830 sq ft",
              "Sq ft"
            ],
            [
              "$812/sq",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 6/9/26: $700K → Price changed 7/13/26: $674K (−$26K). Removed 7/27/26 (off market — note for coordinator).",
          "s5_ownership": "Bought 7/1/21 @ $535K. No rental history on Redfin. Owned ~5 yrs.",
          "s5_hoainc": "Water",
          "s5_parking": "None",
          "s5_storage": "",
          "s5_hvac": "Wall A/C; baseboard heat",
          "s5_laundry": "In-unit W/D",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "STATUS: Conditional (under contract ~7/27/26).",
          "s6_age": "1901",
          "s6_units": "5",
          "s6_amenities": "Intercom",
          "s6_projects": "Hallway in process of being painted (per broker remarks)",
          "s6_assess": "$370,900 (2025)",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Jake Triarsi"
        },
        {
          "seq": "5",
          "addr1": "717 Willow Ave",
          "addr2": "#2 · Hoboken NJ 07030",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "2 BR / 1 BA",
          "time": "",
          "price": "$650,000",
          "agent": "Colleen Kraus · KP&G NJ ·  (contact: Matt Kraus per broker remarks)",
          "phone": "973-891-0616",
          "zillow": "https://www.zillow.com/homedetails/717-Willow-Ave-APT-2-Hoboken-NJ-07030/88857654_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/0/HUDSON_362177.pdf",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "Awaiting confirmation",
          "s2_source": "ShowingTime — Auto Confirm listing (MLS 260014550, Active, 717 Willow Ave #2); no appointment found for 7/28. Needs booking — will Auto Confirm instantly once scheduled.",
          "s3_occupancy": "Vacant (virtually staged per broker remarks)",
          "s3_lb": "",
          "s3_notes": "",
          "snap": [
            [
              "$650K",
              "Asking"
            ],
            [
              "7d",
              "Days on mkt"
            ],
            [
              "$451/mo",
              "HOA/mo"
            ],
            [
              "$6,733 (2025)",
              "Taxes"
            ],
            [
              "800 sq ft",
              "Sq ft"
            ],
            [
              "$813/sq",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/23/26: $650K. No cuts.",
          "s5_ownership": "Bought 12/14/20 @ $530K. No rental history on Zillow. Owned ~5.6 yrs.",
          "s5_hoainc": "Heat, water, hot water",
          "s5_parking": "None",
          "s5_storage": "Deeded private basement storage",
          "s5_hvac": "Window A/C; radiator heat (heat included in HOA)",
          "s5_laundry": "In-unit W/D",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "Split-bedroom layout. Shared backyard w/ patio furniture and grills.",
          "s6_age": "1900",
          "s6_units": "10",
          "s6_amenities": "Intercom; shared backyard with patio and grills",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Jake Triarsi"
        }
      ]
    },
    {
      "deployedAt": "2026-07-27T04:03:25.806424+00:00",
      "meta": {
        "dateLabel": "Mon, July 27",
        "agent": "Christian Daugherty"
      },
      "client": {
        "name": "Elle Dong",
        "fub_url": "https://jillkbiggs.followupboss.com/2/people/view/177066",
        "meta": "1 property · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Appointment set",
        "fields": [
          [
            "Budget",
            "$599,000"
          ],
          [
            "Location",
            "West New York, NJ"
          ]
        ],
        "snapshotLines": [
          "$599,000. Showing today (1 property)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "24 Ave at Port Imperial #B37",
          "addr2": "West New York, NJ 07093",
          "type": "Condo",
          "ptype": "condo",
          "beds": "1 bed / 1 bath",
          "time": "",
          "price": "$575,000",
          "agent": "Mahesh",
          "phone": "929-389-5710",
          "zillow": "https://www.zillow.com/homedetails/24-Avenue-At-Port-Imperial-B37-West-New-York-NJ-07093/2093437559_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/3/HUDSON_360531.pdf",
          "flags": [],
          "s1_time": "",
          "s2_confirmed": "Yes — Confirmed (go-and-show)",
          "s2_source": "Broker remarks: Vacant, go and show. ShowingTime login not accessible this run (occluded window); go-and-show confirmed from MLS broker remarks.",
          "s3_occupancy": "Vacant (go-and-show)",
          "s3_lb": "Not found · Not found",
          "s3_notes": "Not found",
          "snap": [
            [
              "$575K",
              "Asking"
            ],
            [
              "12d",
              "Days on mkt"
            ],
            [
              "$597/mo",
              "HOA/mo"
            ],
            [
              "$10,500/yr (2026)",
              "Taxes"
            ],
            [
              "767 sq ft",
              "Sq ft"
            ],
            [
              "$750/sq",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 5/28: $599K → Price cut 7/15: $575K (-$24K). Actual DOM: 59 days (on market since 5/28/2026)",
          "s5_ownership": "Bought 8/31/22 @ $525K. Owned ~3 yrs 11 mos. No rental history on Zillow. (Prior sale: 6/20/2007 @ $450K.)",
          "s5_hoainc": "Parking",
          "s5_parking": "1 Car, Covered Garage (included in HOA)",
          "s5_storage": "No mention",
          "s5_hvac": "Central AC; heat type not specified — verify at showing",
          "s5_laundry": "In-unit",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "",
          "s6_age": "2004",
          "s6_units": "344 (Hudson Club complex at 24 and 26 Ave at Port Imperial — per hudsonnest.com building profile)",
          "s6_amenities": "Doorman, Exercise Room, Jacuzzi, Pool, Tennis Court, Basketball Courts",
          "s6_projects": "",
          "s6_assess": "",
          "s6_financing": "",
          "s6_key": "Not in property database.",
          "similar": [],
          "commute": [],
          "client_name": "Elle Dong"
        }
      ]
    },
    {
      "deployedAt": "2026-07-25T16:00:05.111484+00:00",
      "meta": {
        "dateLabel": "Sat, July 25",
        "agent": "Christian Daugherty"
      },
      "client": {
        "name": "Catherine Anderson",
        "fub_url": "https://jillkbiggs.followupboss.com/2/people/view/175835",
        "meta": "1 property · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Showing homes",
        "fields": [
          [
            "Budget",
            "$800,000"
          ],
          [
            "Location",
            "Hoboken, NJ"
          ]
        ],
        "snapshotLines": [
          "$800,000. Showing today (1 property)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "1032 Willow Ave #3",
          "addr2": "Hoboken, NJ 07030",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "3 BR",
          "time": "12:00 PM",
          "price": "$850,000",
          "agent": "Gerard A Mattera Jr",
          "phone": "(917) 693-1233",
          "zillow": "https://www.zillow.com/homedetails/1032-Willow-Ave-APT-3-Hoboken-NJ-07030/2126559974_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/6/HUDSON_359620.pdf",
          "flags": [],
          "s1_time": "12:00 PM",
          "s2_confirmed": "Yes — Confirmed",
          "s2_source": "Christian confirmed visually in his ShowingTime app ~11:50 AM 7/25. NOTE: overnight sub-agent falsely reported 'My Showings (0)' — automation browser's ST app was serving a stale 7/24 cache (occluded-window no-sync bug, root-caused 7/25).",
          "s3_occupancy": "Occupied — clarify: seller or tenant?",
          "s3_lb": "",
          "s3_notes": "CONFIRMED showing 12:00 PM (per Christian, ST app). Lockbox/access details not retrieved — automation browser's ShowingTime data sync is dead in the off-screen window (root-caused 7/25; fleet fix pending). LA: Gerard Mattera Jr (917) 693-1233.",
          "snap": [
            [
              "$850K",
              "Asking"
            ],
            [
              "17",
              "Days on mkt"
            ],
            [
              "$351/mo",
              "HOA/mo"
            ],
            [
              "$8,135/yr (2025)",
              "Taxes"
            ],
            [
              "992 sqft",
              "Sq ft"
            ],
            [
              "$857/sqft",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/8: $850,000 (no price changes)",
          "s5_ownership": "Bought 12/21/2020 @ $710,000. Owned ~4.6 yrs. Listed for rent 7/9/2023 at $2,775/mo (removed 7/28/2023 — assumed rented). Note: Zillow 'Show more' not expandable (viewport issue in this session); pre-2020 sale history not confirmed.",
          "s5_hoainc": "No mention",
          "s5_parking": "None",
          "s5_storage": "Storage (per common amenities: Security, Storage)",
          "s5_hvac": "A/C Wall, Baseboard, Gas",
          "s5_laundry": "In-unit washer/dryer",
          "s5_flood": "Zone X (No)",
          "s5_misc": "Intercom, Hardwood Floor, Fireplace, 10-ft ceilings, granite countertops, soaking tub; inclusions: appliances as installed; exclusions: personal property",
          "s6_age": "1901",
          "s6_units": "8 — 7 residential + 1 ground-floor commercial (taxed as 1030 Willow, per tax records)",
          "s6_amenities": "Security, Intercom, Storage",
          "s6_projects": "",
          "s6_assess": "No mention",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Catherine Anderson"
        }
      ]
    },
    {
      "deployedAt": "2026-07-25T16:00:05.111484+00:00",
      "meta": {
        "dateLabel": "Sat, July 25",
        "agent": "Christian Daugherty"
      },
      "client": {
        "name": "Mina Nedjari",
        "fub_url": "https://jillkbiggs.followupboss.com/2/people/view/217741",
        "meta": "2 properties · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Appointment set",
        "fields": [
          [
            "Budget",
            "$1,800"
          ],
          [
            "Location",
            "Jersey City Heights / Bayonne, NJ"
          ],
          [
            "Timeline",
            "0-3 months"
          ]
        ],
        "snapshotLines": [
          "$1,800. Showing today (2 properties)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "113 W 2nd St #2",
          "addr2": "Bayonne, NJ 07002",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "1 BR",
          "time": "10:00 AM",
          "price": "$190,000",
          "agent": "Lissa Ruge",
          "phone": "(551) 227-1309",
          "zillow": "https://www.zillow.com/homedetails/113-W-2nd-St-2-Bayonne-NJ-07002/2128256812_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/0/HUDSON_362054.pdf",
          "flags": [],
          "s1_time": "10:00 AM",
          "s2_confirmed": "Awaiting confirmation",
          "s2_source": "ShowingTime calendar My Showings=0 on 7/25 after hydration. Listing confirmed active in ShowingTime (ID 174684778, HCMLS 260014580). No existing appointment found for 7/25. No Auto Confirm badge. Access details tab not rendered in current session (Ionic shadow DOM). No explicit text-to-schedule signal in available data.",
          "s3_occupancy": "Occupied — clarify: seller or tenant?",
          "s3_lb": "",
          "s3_notes": "No ShowingTime appointment confirmed for 7/25. Access details not available — no confirmed appointment to pull from. Contact listing agent Lissa Ruge (551) 227-1309 to verify access before showing.",
          "snap": [
            [
              "$190K",
              "Asking"
            ],
            [
              "2",
              "Days on mkt"
            ],
            [
              "$432/mo",
              "HOA/mo"
            ],
            [
              "$3,533/yr",
              "Taxes"
            ],
            [
              "450 sqft",
              "Sq ft"
            ],
            [
              "$422/sqft",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/23: $190,000 (no price changes)",
          "s5_ownership": "No Sold event on Zillow, Redfin, or Google. Zillow shows rental listing 2/7/2011 at $900/mo (removed 5/17/2011). No prior sale confirmed — owner appears long-term holder (pre-2011). Not found after full web search.",
          "s5_hoainc": "Heat, hot water, common area maintenance, snow removal",
          "s5_parking": "1 designated spot",
          "s5_storage": "Private storage cage",
          "s5_hvac": "A/C Window; Radiators",
          "s5_laundry": "No mention",
          "s5_flood": "Zone X (No)",
          "s5_misc": "",
          "s6_age": "1950",
          "s6_units": "20 (complex spans 99-113 W 2nd St per Bayonne tax records; 2-story brick condo)",
          "s6_amenities": "None",
          "s6_projects": "",
          "s6_assess": "$305.38/mo, started Feb 2026, will last 12-18 months",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Mina Nedjari"
        },
        {
          "seq": "2",
          "addr1": "214 AVENUE A, Unit B5",
          "addr2": "Bayonne, NJ 07002",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "2 BR",
          "time": "10:00 AM",
          "price": "$269,000",
          "agent": "Christopher Piechocki",
          "phone": "(201) 978-1110",
          "zillow": "Not found — no active Zillow listing identified for '214 Avenue #A'. Address may be incomplete or unlisted. MLS step must search HCMLS directly.",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/2/HUDSON_357297.pdf",
          "flags": [],
          "s1_time": "10:00 AM",
          "s2_confirmed": "Awaiting confirmation",
          "s2_source": "ShowingTime calendar My Showings=0 on 7/25 after hydration. Listing found in ShowingTime as '214 AVENUE A, B5' (ID 173468708) — unit mismatch: appointment title shows unit A but ShowingTime/MLS show unit B5. No existing appointment for 7/25. No Auto Confirm badge. No explicit text-to-schedule signal in available data.",
          "s3_occupancy": "Occupied — clarify: seller or tenant?",
          "s3_lb": "",
          "s3_notes": "No ShowingTime appointment for 7/25. UNIT DISCREPANCY: appointment says unit A, but ShowingTime/HCMLS show unit B5 under MLS 260011832 — confirm correct unit with LA Christopher Piechocki (201) 978-1110 before arriving. Access details unknown.",
          "snap": [
            [
              "$269K",
              "Asking"
            ],
            [
              "38",
              "Days on mkt"
            ],
            [
              "$320/mo",
              "HOA/mo"
            ],
            [
              "$4,804/yr (2025)",
              "Taxes"
            ],
            [
              "602 sqft",
              "Sq ft"
            ],
            [
              "$447/sqft",
              "Per sq ft"
            ]
          ],
          "s5_history": "Not found — no active Zillow listing identified for '214 Avenue #A'. Address appears ambiguous (no specific avenue name).",
          "s5_ownership": "Not found — no Zillow listing identified. Fallback search also unsuccessful. MLS step must determine and coordinator should flag address to Christian for clarification.",
          "s5_hoainc": "No mention",
          "s5_parking": "2 tandem spots (deeded per advertising remarks; MLS features: Tandem-Shared)",
          "s5_storage": "No mention",
          "s5_hvac": "A/C Wall",
          "s5_laundry": "Building laundry room",
          "s5_flood": "Not found — no Zillow listing identified; flood zone could not be determined.",
          "s5_misc": "Hardwood floors, recessed lighting; inclusions: all major appliances; exclusions: all personal items",
          "s6_age": "Built ~1965 (Bayonne tax records; Trulia public facts show 1950 — confirm at showing)",
          "s6_units": "25 (West Bay Condominiums, 3-story brick, per tax records)",
          "s6_amenities": "None",
          "s6_projects": "",
          "s6_assess": "No mention",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Mina Nedjari"
        }
      ]
    },
    {
      "deployedAt": "2026-07-25T16:00:05.111484+00:00",
      "meta": {
        "dateLabel": "Sat, July 25",
        "agent": "Christian Daugherty"
      },
      "client": {
        "name": "Manmeet Chawla",
        "fub_url": "https://jillkbiggs.followupboss.com/2/people/view/219848",
        "meta": "1 property · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Appointment set",
        "fields": [
          [
            "Budget",
            "$1,499,000"
          ],
          [
            "Location",
            "Jersey City, NJ"
          ]
        ],
        "snapshotLines": [
          "$1,499,000. Showing today (1 property)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "73 Palisade Ave #1",
          "addr2": "Jersey City, NJ 07306",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "1 BR",
          "time": "11:30 AM",
          "price": "$296,000",
          "agent": "Samir Y Genid",
          "phone": "(973) 271-1666",
          "zillow": "https://www.zillow.com/homedetails/73-Palisade-Ave-1-Jersey-City-NJ-07306/2111066501_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/6/HUDSON_360223.pdf",
          "flags": [],
          "s1_time": "11:30 AM",
          "s2_confirmed": "Awaiting confirmation",
          "s2_source": "FUB appointment description says [Requested] status in ShowingTime, but ShowingTime calendar My Showings=0 on 7/25 after hydration. Listing confirmed active in ShowingTime (ID 174285790, 73 PALISADE AVE, 1). Discrepancy — request may have been declined, expired, or submitted under different account. No Auto Confirm badge.",
          "s3_occupancy": "Occupied — clarify: seller or tenant?",
          "s3_lb": "",
          "s3_notes": "STATUS DISCREPANCY — FUB shows [Requested] in ShowingTime but ST calendar shows 0 appointments on 7/25. Showing is at 11:30 AM — verify confirmation status immediately with listing agent Samir Genid (973) 271-1666 before arriving. Access details unknown.",
          "snap": [
            [
              "$296K",
              "Asking"
            ],
            [
              "15",
              "Days on mkt"
            ],
            [
              "$220/mo",
              "HOA/mo"
            ],
            [
              "$5,017/yr (2025)",
              "Taxes"
            ],
            [
              "438 sqft",
              "Sq ft"
            ],
            [
              "$676/sqft",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 7/10: $296,000 (no price changes)",
          "s5_ownership": "No Sold event on Zillow or Redfin. Redfin shows prior listing Jun 2006 at $199K (sale not confirmed in public record). Zillow shows rental 9/11/2013 at $1,100/mo (removed 9/17/2013). Owner appears long-term holder (pre-2006). Not found after full web search.",
          "s5_hoainc": "Common area maintenance",
          "s5_parking": "None",
          "s5_storage": "No mention",
          "s5_hvac": "A/C Window, Gas",
          "s5_laundry": "No mention",
          "s5_flood": "Zone X (No)",
          "s5_misc": "All furniture included (inclusions: all personal items/furniture); all appliances excluded; private backyard",
          "s6_age": "1900",
          "s6_units": "6 (association spans 73 & 75 Palisade per Hudson County tax records)",
          "s6_amenities": "Private Backyard",
          "s6_projects": "",
          "s6_assess": "No mention",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "Manmeet Chawla"
        }
      ]
    },
    {
      "deployedAt": "2026-07-25T16:00:05.111484+00:00",
      "meta": {
        "dateLabel": "Sat, July 25",
        "agent": "Christian Daugherty"
      },
      "client": {
        "name": "noclient",
        "fub_url": "",
        "meta": "1 property · Buyer · Christian Daugherty, Jill Biggs Group",
        "stage": "Active buyer",
        "fields": [],
        "snapshotLines": [
          "Showing today (1 property)."
        ]
      },
      "props": [
        {
          "seq": "1",
          "addr1": "24 Avenue at Port Imperial #B37",
          "addr2": "West New York, NJ 07093",
          "type": "Condominium",
          "ptype": "condo",
          "beds": "1 BR",
          "time": "1:00 PM (OH 1-3 PM)",
          "price": "$575,000",
          "agent": "Jill K Biggs ·  (Coldwell Banker / Jill Biggs Group — Christian's office)",
          "phone": "(973) 495-6038",
          "zillow": "https://www.zillow.com/homedetails/24-Avenue-At-Port-Imperial-B37-West-New-York-NJ-07093/2093437559_zpid/",
          "nav_addr": "",
          "disclosure": "https://hudson.paragonrels.com/ParagonLS/Files/AssociatedDocs/HUDSON/3/HUDSON_360531.pdf",
          "flags": [],
          "s1_time": "1:00 PM (OH 1-3 PM)",
          "s2_confirmed": "Yes — Confirmed (Auto Confirm)",
          "s2_source": "ShowingTime — Auto Confirm badge on listing card (ID 174404599, MLS 260013863). Vacant per MLS occupancy_hint. JBG own listing (Coldwell Banker / Jill Biggs Group). Auto Confirm = instant approval; no pre-booked appointment needed for go-and-show access.",
          "s3_occupancy": "Vacant (go-and-show)",
          "s3_lb": "",
          "s3_notes": "Own JBG / Coldwell Banker listing — Christian is the contact. Vacant, Auto Confirm, go-and-show. Lockbox/access details not retrieved from ShowingTime scheduling tab (Ionic shadow DOM not rendering in current session). Christian should know building access for own listing. Open house 7/25 & 7/26 1pm–3pm.",
          "snap": [
            [
              "$575K",
              "Asking"
            ],
            [
              "10",
              "Days on mkt"
            ],
            [
              "$597/mo",
              "HOA/mo"
            ],
            [
              "$10,500/yr (2026 — verify with city tax assessor)",
              "Taxes"
            ],
            [
              "767 sqft",
              "Sq ft"
            ],
            [
              "$750/sqft",
              "Per sq ft"
            ]
          ],
          "s5_history": "Listed 5/28: $599,000 → Price cut 7/15: $575,000 (-$24K)",
          "s5_ownership": "Bought 8/31/2022 @ $525,000. Owned ~2.9 yrs. No rental history on Zillow since purchase. Note: Zillow 'Show more' not expandable (viewport issue); pre-2022 sale history not confirmed.",
          "s5_hoainc": "Parking (deeded spot #57)",
          "s5_parking": "1 Car, Covered, Garage (deeded spot #57; included in HOA)",
          "s5_storage": "Built-in shelving system in bedroom closet (per advertising)",
          "s5_hvac": "A/C Central",
          "s5_laundry": "In-unit washer/dryer",
          "s5_flood": "Zone AE (Yes)",
          "s5_misc": "Private terrace, Hardwood Floor, NY/river views; inclusions: appliances and light fixtures as installed; exclusions: all personal possessions; only 1 neighbor on same floor; direct garage access from unit; quartz countertops; custom barn door in bedroom",
          "s6_age": "~2002-2004 (Hudson Club; sources conflict — likely phased completion)",
          "s6_units": "172 in this building (Hudson Club complex = 344 units across 24 & 26 Ave at Port Imperial)",
          "s6_amenities": "Doorman (24-7 concierge), Exercise Room, Jacuzzi, Pool, Tennis Court, Basketball Courts, Business Center, Children's Play Area, On-site security",
          "s6_projects": "",
          "s6_assess": "No mention",
          "s6_financing": "",
          "s6_key": "",
          "similar": [],
          "commute": [],
          "client_name": "noclient"
        }
      ]
    }
  ]
};
// v3-cutover-ping 2026-08-02T20:08-0400
